'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Trophy,Crosshair,Map,BookOpen,Shield,ArrowRight,Check,Search,SlidersHorizontal,Download,Upload,Save,RotateCcw,GitBranch,ChevronRight,ExternalLink,Info,Eye,EyeOff,Settings2,Plus,Minus,CheckCheck,Flag,HardDrive,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import {Checkbox} from '@/components/ui/checkbox';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {achievements,decisions,groups,sources,stages,type Achievement,type Group,type StageId} from '@/lib/tracker-data';
import {freshRun,freshState,parseState,status,storageKey,type FlagId,type Run,type TrackerState} from '@/lib/tracker-state';

type View='now'|'all'|'route'|'collection';
type Modal='stage'|'decisions'|'progress'|'snapshots'|null;
type Confirmation={title:string;body:string;action:()=>void};
type ModelTool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
type ModelContext={registerTool:(tool:ModelTool,options:{signal:AbortSignal})=>void|Promise<void>};
const flagLabels:Record<FlagId,{title:string;good:string;bad:string}>={kills:{title:'Пацифист',good:'Убийств не было',bad:'Было убийство'},alarms:{title:'Проныра',good:'Тревог не было',bad:'Была тревога'},systemKills:{title:'Чисто, чисто, чисто, чисто!',good:'Убийств не было',bad:'Было убийство'},criminalKills:{title:'Все по правилам',good:'Убийств не было',bad:'Было убийство'},drugs:{title:'Без допинга',good:'Ничего не использовал',bad:'Использовал таблетку / батарею'}};
function Pick({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){
return <Select value={value} onValueChange={v=>{if(v!==null)onChange(v)}}><SelectTrigger aria-label={label} className="pick"><SelectValue>{options.find(o=>o.value===value)?.label||label}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;
}
const pad=(n:number)=>String(n).padStart(2,'0');
export default function Home(){
const [state,setState]=useState<TrackerState>(freshState);
const stateRef=useRef(state);stateRef.current=state;
const [ready,setReady]=useState(false),[storageSafe,setStorageSafe]=useState(true),[storageError,setStorageError]=useState('');
const [view,setView]=useState<View>('now'),[modal,setModal]=useState<Modal>(null),[detail,setDetail]=useState<Achievement|null>(null),[confirm,setConfirm]=useState<Confirmation|null>(null);
const [search,setSearch]=useState(''),[filter,setFilter]=useState('todo'),[group,setGroup]=useState('all'),[notice,setNotice]=useState(''),[stageTarget,setStageTarget]=useState<StageId>('dubai'),[snapshotName,setSnapshotName]=useState('');
const importInput=useRef<HTMLInputElement>(null);
useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw)setState(parseState(JSON.parse(raw)));}catch{setStorageSafe(false);setStorageError('Не удалось прочитать сохранение. Оно не перезаписано. Можно импортировать резервную копию.');}setReady(true)},[]);
useEffect(()=>{if(!ready||!storageSafe)return;try{localStorage.setItem(storageKey,JSON.stringify(state));setStorageError('')}catch{setStorageError('Не удалось сохранить в браузере. Экспортируй прогресс в файл.')}},[state,ready,storageSafe]);
useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice]);
useEffect(()=>{
const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;
const lifecycle=new AbortController();
const read=()=>({stage:stateRef.current.run.stage,earned:stateRef.current.earned,total:achievements.length,books:stateRef.current.run.books});
for(const tool of [
{name:'get_tracker_progress',title:'Прочитать прогресс',description:'Read manually recorded achievements and the current game stage. Does not access the game or Steam.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>read()},
{name:'set_achievements',title:'Отметить достижения',description:'Manually mark a batch of achievement IDs as earned or not earned. Does not change story decisions or run conditions.',inputSchema:{type:'object',properties:{ids:{type:'array',items:{type:'string'}},earned:{type:'boolean'}},required:['ids','earned'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{
if(!input||typeof input!=='object')throw Error('Expected an object');const v=input as {ids?:unknown;earned?:unknown};
if(!Array.isArray(v.ids)||!v.ids.every(id=>typeof id==='string'&&achievements.some(a=>a.id===id))||typeof v.earned!=='boolean')throw Error('Invalid achievement IDs or earned flag');
const ids=v.ids as string[];flushSync(()=>setState(s=>({...s,earned:v.earned?[...new Set([...s.earned,...ids])]:s.earned.filter(id=>!ids.includes(id))})));return read();
}}] satisfies ModelTool[]){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}
return()=>lifecycle.abort();
},[]);
const run=state.run,stage=stages.find(s=>s.id===run.stage)!,stageIndex=stages.findIndex(s=>s.id===run.stage);
const eligible=achievements.filter(a=>a.stages.includes(run.stage));
const focused=eligible.filter(a=>a.stages.length<=2||a.id==='ghost'||(a.kind==='run'&&run.stage==='credits'));
const flexible=eligible.filter(a=>!focused.includes(a));
const earnedHere=eligible.filter(a=>state.earned.includes(a.id)).length;
const scoped=achievements.filter(a=>a.group===stage.group);
const earnedScope=scoped.filter(a=>state.earned.includes(a.id)).length;
function updateRun(patch:Partial<Run>){setState(s=>({...s,run:{...s.run,...patch}}))}
function mark(id:string,value:boolean){setState(s=>({...s,earned:value?[...new Set([...s.earned,id])]:s.earned.filter(x=>x!==id)}))}
function changeStage(id:StageId){updateRun({stage:id});setModal(null);setView('now');setNotice('Этап обновлён. Достижения и решения сохранены.')}
function openStage(){setStageTarget(run.stage);setModal('stage')}
function setCounter(id:string,value:number,max:number){const n=Math.max(0,Math.min(max,Math.trunc(Number.isFinite(value)?value:0)));if(id==='books')updateRun({books:n});else updateRun({counters:{...run.counters,[id]:n}})}
function exportProgress(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='deus-ex-progress-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Копия прогресса сохранена в файл.')}
async function importProgress(file:File|undefined){if(!file)return;try{if(file.size>2000000)throw Error('Файл слишком большой.');const next=parseState(JSON.parse(await file.text()));setConfirm({title:'Загрузить прогресс из файла?',body:'Текущие отметки, решения и контрольные точки будут заменены. При необходимости сначала экспортируй текущий прогресс.',action:()=>{setState(next);setStorageSafe(true);setModal(null);setNotice('Прогресс восстановлен.')}})}catch(e){setNotice(e instanceof Error?e.message:'Не удалось прочитать файл.')}finally{if(importInput.current)importInput.current.value=''}}
function saveSnapshot(){if(state.snapshots.length>=12){setNotice('Сохранено 12 точек. Удали ненужную, чтобы добавить новую.');return}const name=snapshotName.trim()||stage.short+' · '+new Date().toLocaleDateString('ru-RU');setState(s=>({...s,snapshots:[{id:crypto.randomUUID(),name,createdAt:new Date().toISOString(),run:structuredClone(s.run)},...s.snapshots]}));setSnapshotName('');setNotice('Состояние трекера сохранено. Сохранение игры сделай отдельно.')}
function isHidden(a:Achievement){return !!a.secret&&!state.spoilers&&!state.earned.includes(a.id)&&(a.group!==stage.group||Math.min(...a.stages.map(id=>stages.findIndex(s=>s.id===id)))>stageIndex)}
function Meter({label,value,max}:{label:string;value:number;max:number}){return <div className="stat"><span>{label}</span><strong>{pad(value)}<small>/ {max}</small></strong><Progress value={max?value/max*100:0} aria-label={label}/></div>}
function Counter({id,label,value,max}:{id:string;label:string;value:number;max:number}){return <div className="counter"><Button variant="outline" size="icon" aria-label={'Уменьшить: '+label} disabled={!value} onClick={()=>setCounter(id,value-1,max)}><Minus/></Button><Input aria-label={label} type="number" min={0} max={max} value={value} onChange={e=>setCounter(id,Number(e.target.value),max)}/><span>/ {max}</span><Button variant="outline" size="icon" aria-label={'Увеличить: '+label} disabled={value>=max} onClick={()=>setCounter(id,value+1,max)}><Plus/></Button></div>}
function Item({a}:{a:Achievement}){const s=status(a,state),hidden=isHidden(a),done=state.earned.includes(a.id);return <article key={a.id} className={'achievement '+(done?'is-done':'')}><div className="achievement-icon">{done?<Check/>:a.kind==='collect'?<BookOpen/>:a.kind==='combat'?<Crosshair/>:a.kind==='run'?<Shield/>:<Trophy/>}</div><div className="achievement-body"><span className="eyebrow">{a.category} · {a.stages.length>2?'ПО ХОДУ ИГРЫ':a.stages.map(id=>stages.find(s=>s.id===id)?.short).join(' / ')}</span><button className="title-button" onClick={()=>setDetail(a)}><h3>{hidden?'Скрытое достижение':a.name}<ChevronRight size={13}/></h3></button><p>{hidden?'Описание откроется на соответствующем этапе.':a.description}</p><span className={'tag '+s.tone}>{s.label}</span>{a.kind==='combat'&&run.goals.length>0&&!done&&<span className="tag neutral">Сохранись перед попыткой</span>}{s.detail&&!hidden&&<p className="blocker">{s.detail}</p>}</div><Checkbox aria-label={'Получено: '+(hidden?'скрытое достижение '+a.id:a.name)} checked={done} onCheckedChange={v=>mark(a.id,v)}/></article>}
function FlagControl({id}:{id:FlagId}){const f=flagLabels[id];return <div className="flag-control" key={id}><label>{f.title}</label><Pick label={f.title} value={run.flags[id]} options={[{value:'unknown',label:'Не уверен / не отмечено'},{value:'clear',label:f.good},{value:'broken',label:f.bad}]} onChange={v=>updateRun({flags:{...run.flags,[id]:v as Run['flags'][FlagId]}})}/><span className={'flag-hint '+run.flags[id]}>{run.flags[id]==='clear'?'По твоим отметкам условие сохранено':run.flags[id]==='broken'?'Нужен откат или другое прохождение':'Подтверди состояние вручную'}</span></div>}
function SidePanel(){const keys:FlagId[]=stage.group==='campaign'?['kills','alarms']:stage.group==='system'?['systemKills']:stage.group==='criminal'?['criminalKills','drugs']:[];return <aside><div className="side-card"><div className="eyebrow"><Shield size={15}/>{keys.length?'НА ВСЁ ПРОХОЖДЕНИЕ':'ПРОГРЕСС РЕЖИМА'}</div><h3>{stage.group==='campaign'?'Чистая работа':groups[stage.group]}</h3><p>{keys.length?'Обновляй условия после важных событий.':'Сетевые достижения отмечаются вручную.'}</p>{keys.map(id=>FlagControl({id}))}{stage.group==='campaign'&&<div className="goals"><span className="eyebrow">МОИ ЦЕЛИ</span>{[['pacifist','Без убийств'],['fox','Без тревог']].map(([id,label])=><label key={id}><Checkbox checked={run.goals.includes(id)} onCheckedChange={v=>updateRun({goals:v?[...run.goals,id]:run.goals.filter(x=>x!==id)})}/>{label}</label>)}</div>}</div><div className="note-card"><span className="eyebrow"><Flag size={13}/>ПЕРЕД УХОДОМ</span><h3>Проверь, прежде чем идти дальше</h3><p>{stage.before}</p><Button variant="ghost" className="text-action" onClick={()=>setModal('snapshots')}><Save size={13}/> Сохранить точку</Button></div><div className="note-card sources"><span className="eyebrow">ПОЛЕЗНЫЕ МАТЕРИАЛЫ</span><a href={sources.guide} target="_blank" rel="noreferrer">Исходное руководство <ExternalLink size={12}/></a><a href={sources.roadmap} target="_blank" rel="noreferrer">Развилки и прохождение <ExternalLink size={12}/></a><p>Подсказки для MVP. Фактическое получение проверяй в игре или Steam.</p></div></aside>}
const filtered=achievements.filter(a=>(group==='all'||a.group===group)&&(filter==='all'||(filter==='earned'?state.earned.includes(a.id):filter==='now'?status(a,state).tone==='now':!state.earned.includes(a.id)))&&(!search.trim()||(!isHidden(a)&&(a.name+' '+a.description).toLocaleLowerCase('ru').includes(search.trim().toLocaleLowerCase('ru')))));
const applicableDecisions=decisions.filter(d=>stage.group==='campaign'&&stages.findIndex(s=>s.id===d.stage)<=stageIndex);
return <div className="app-shell" aria-busy={!ready}>
<aside className="sidebar"><a href="/" className="brand" aria-label="Deus Ex Achievement Protocol"><span className="brand-symbol">DX</span><span>DEUS EX<small>ACHIEVEMENT PROTOCOL</small></span></a><div className="sidebar-label">ЛИЧНОЕ ДОСЬЕ / 01</div><nav aria-label="Разделы трекера">{([{id:'now',label:'Сейчас',icon:Crosshair,count:focused.filter(a=>!state.earned.includes(a.id)).length},{id:'all',label:'Достижения',icon:Trophy,count:81},{id:'route',label:'Маршрут',icon:Map},{id:'collection',label:'Коллекция',icon:BookOpen}] as const).map(n=><Button key={n.id} variant="ghost" className={'nav-item '+(view===n.id?'active':'')} onClick={()=>setView(n.id)} aria-current={view===n.id?'page':undefined}><n.icon/>{n.label}{'count'in n&&<span>{pad(n.count)}</span>}</Button>)}</nav><div className="sidebar-secondary"><Button variant="ghost" className="nav-item" onClick={()=>setModal('snapshots')}><Save/>Контрольные точки</Button><Button variant="ghost" className="nav-item" onClick={()=>setModal('progress')}><Settings2/>Мой прогресс</Button></div><div className="sidebar-bottom"><span className="status-dot"/>{!ready?'Загрузка прогресса':storageError?'Есть проблема сохранения':'Прогресс в этом браузере'}<p>Твой маршрут. Твои решения.</p></div></aside>
<div className="workspace"><header className="topbar"><span>MANKIND DIVIDED <b>/</b> ТРЕКЕР ПРОХОЖДЕНИЯ</span><Button variant="ghost" size="sm" className="top-save" onClick={exportProgress}><Download size={12}/> Экспорт</Button></header>
<main>{storageError&&<div className="storage-warning" role="alert"><Info size={16}/>{storageError}<Button variant="outline" onClick={()=>setModal('progress')}>Мой прогресс</Button></div>}
<div className="page-heading"><div><div className="eyebrow">{view==='now'?'ОПЕРАЦИЯ ПРОДОЛЖАЕТСЯ':view==='all'?'АРХИВ ДОСТИЖЕНИЙ':view==='route'?'ПЛАН ОПЕРАЦИИ':'БАЗА ДАННЫХ'}</div><h1>{view==='now'?'Каждый выбор имеет значение':view==='all'?'Досье на 81 достижение':view==='route'?'Твой путь через систему':'Ничего не упустить'}<span>.</span></h1><p>{view==='now'?'Отмечай сделанное. Следи за условиями. Не упускай возможности.':view==='all'?'Одна отметка — ещё один шаг к полному прохождению.':view==='route'?'Выбирай этап вручную и фиксируй решения в текущей ветке.':'Счётчики отражают только то, что ты внесёшь сам.'}</p></div><button className="spoiler-toggle" onClick={()=>setState(s=>({...s,spoilers:!s.spoilers}))} aria-pressed={state.spoilers}>{state.spoilers?<Eye size={15}/>:<EyeOff size={15}/>}<span>{state.spoilers?'Спойлеры открыты':'Без будущих спойлеров'}</span></button></div>
<section className="mission-banner"><div className="mission-number">{pad(stageIndex+1)}</div><div><div className="eyebrow">ТЕКУЩИЙ ЭТАП · {stage.mission}</div><h2>{stage.name}</h2><p>{stage.subtitle}</p></div><Button variant="outline" onClick={openStage}>Изменить этап <ArrowRight/></Button></section>
<div className="stats-grid">{Meter({label:"ВСЕ ДОСТИЖЕНИЯ",value:state.earned.length,max:81})}{Meter({label:view==='all'?'В ТЕКУЩЕМ РЕЖИМЕ':'НА ЭТОМ ЭТАПЕ',value:view==='all'?earnedScope:earnedHere,max:view==='all'?scoped.length:eligible.length})}{Meter({label:"ЭЛЕКТРОННЫЕ КНИГИ",value:run.books,max:75})}</div>
{view==='now'&&<div className="content-grid"><section>
<div className="section-heading"><h2>Сделать сейчас</h2><span>{pad(focused.filter(a=>!state.earned.includes(a.id)).length)} ОСТАЛОСЬ</span></div>
{focused.length>0?<div className="achievement-list">{focused.map(a=>Item({a}))}</div>:<div className="empty-state"><CheckCheck/><h3>Проверь общие задачи</h3><p>На этом этапе доступны задачи, которые можно выполнить по ходу игры.</p></div>}
{focused.length>0&&focused.every(a=>state.earned.includes(a.id))&&<div className="complete-note"><CheckCheck size={18}/>Все задачи этого списка отмечены. Проверь книги и условия перед переходом.</div>}
{flexible.length>0&&<details className="flexible"><summary>Также можно выполнить по ходу игры <span>{flexible.length}</span></summary><div className="achievement-list">{flexible.map(a=>Item({a}))}</div></details>}
{stage.group==='campaign'&&applicableDecisions.length>0&&<div className="decision-callout"><GitBranch/><div><h3>У каждого решения есть последствия</h3><p>Обнови журнал, чтобы видеть закрытые варианты.</p></div><Button variant="outline" onClick={()=>setModal('decisions')}>Мои решения</Button></div>}
<div className="next-stage"><span>{stage.group==='campaign'?'Перед переходом проверь список справа.':'Можно вернуться в любой режим.'}</span><Button variant="outline" onClick={()=>{setStageTarget(stages[Math.min(stageIndex+1,stages.length-1)].id);setModal('stage')}}>Выбрать следующий этап <ArrowRight/></Button></div>
</section>{SidePanel()}</div>}
{view==='all'&&<section><div className="filters"><div className="search-field"><Search size={17}/><Input placeholder="Поиск по названию или условию…" aria-label="Поиск достижений" value={search} onChange={e=>setSearch(e.target.value)}/></div><Pick label="Режим" value={group} onChange={setGroup} options={[{value:'all',label:'Все режимы'},...Object.entries(groups).map(([value,label])=>({value,label}))]}/><Pick label="Статус" value={filter} onChange={setFilter} options={[{value:'todo',label:'Не получены'},{value:'all',label:'Все достижения'},{value:'earned',label:'Получены'},{value:'now',label:'Доступны сейчас'}]}/></div><div className="section-heading"><h2>{filter==='earned'?'Полученные достижения':'Список достижений'}</h2><span>{filtered.length} / 81</span></div>{filtered.length?<div className="achievement-list archive">{filtered.map(a=>Item({a}))}</div>:<div className="empty-state"><Search/><h3>Ничего не найдено</h3><p>Измени запрос или фильтры. Будущие секреты скрыты, пока выключены спойлеры.</p><Button variant="outline" onClick={()=>{setSearch('');setGroup('all');setFilter('all')}}>Сбросить фильтры</Button></div>}<p className="micro-copy">«Закрыто выбором» относится к текущей ветке. Уже полученные достижения остаются в архиве.</p></section>}
{view==='route'&&<div className="content-grid"><section><div className="section-heading"><h2>Карта прохождения</h2><span>ЭТАПЫ И РАЗВИЛКИ</span></div><p className="route-note">Схема последовательности, не географическая карта. Нажми этап, чтобы сделать его текущим.</p><ol className="route-map">{stages.slice(0,8).map((s,i)=>{const count=achievements.filter(a=>a.stages.includes(s.id)&&a.stages.length<=2);return <li className={run.stage===s.id?'current':''} key={s.id}><button className="route-step" onClick={()=>changeStage(s.id)}><span className="route-node">{pad(i+1)}</span><span><small>{s.mission}</small><strong>{s.short}</strong><em>{state.earned.filter(id=>count.some(a=>a.id===id)).length} / {count.length} достижений этапа</em></span>{run.stage===s.id?<span className="tag">ТЫ ЗДЕСЬ</span>:<ChevronRight size={16}/>}</button>{['prague1','prague2','london'].includes(s.id)&&<div className="route-fork"><GitBranch size={13}/>{s.id==='prague1'?'Калибратор: до встречи или после просьбы':s.id==='prague2'?'Развилка: Элисон или банк':state.spoilers||stageIndex>=6?'Финал: нелетально или устройство':'В финале есть важное решение'}</div>}</li>})}</ol><div className="dlc-routes">{stages.slice(8).map(s=><Button variant="outline" key={s.id} onClick={()=>changeStage(s.id)}>{s.short}<ArrowRight size={14}/></Button>)}</div><div className="section-heading journal-heading"><h2>Журнал решений</h2><Button variant="outline" onClick={()=>setModal('decisions')}><SlidersHorizontal/>Обновить</Button></div>{applicableDecisions.length?<div className="journal">{applicableDecisions.map(d=><div key={d.id}><span>{d.title}</span><strong>{d.options.find(o=>o.value===run.decisions[d.id])?.label||'Ещё не отмечено'}</strong></div>)}</div>:<p>Журнал основной кампании появится с первого посещения Праги.</p>}</section>{SidePanel()}</div>}
{view==='collection'&&<div className="content-grid"><section><div className="collection-panel"><div className="eyebrow"><BookOpen size={16}/>КОЛЛЕКЦИОНЕР ПЛАНШЕТОВ</div><h2>75 фрагментов мира</h2><p>Внеси число уникальных книг из базы данных игры. Счётчик относится к текущему прохождению.</p><div className="book-count">{Counter({id:"books",label:"Количество прочитанных книг",value:run.books,max:75})}<strong>{Math.round(run.books/75*100)}<small>%</small></strong></div><Progress value={run.books/75*100} aria-label="Собрано книг"/><p className="micro-copy">75 / 75 не отмечает достижение автоматически. Проверь его получение и поставь галочку в списке.</p><div className="book-warning"><Info size={17}/><p>Книги не переносятся в NG+. Нужна банковская ветка и доступ к «Последнему урожаю». В MVP используется общий счётчик, без разметки каждого планшета.</p></div><a className="external-button" href={sources.books} target="_blank" rel="noreferrer">Видео: все 75 книг по порядку <ExternalLink size={14}/></a></div><div className="section-heading journal-heading"><h2>Счётчики Breach</h2><span>ВРУЧНУЮ</span></div><div className="counter-list">{achievements.filter(a=>a.group==='breach'&&a.counter&&a.counter>1).map(a=><div className="counter-row" key={a.id}><div><h3>{a.name}</h3><p>{a.description}</p><Progress value={(run.counters[a.id]||0)/a.counter!*100} aria-label={a.name}/></div>{Counter({id:a.id,label:a.name,value:run.counters[a.id]||0,max:a.counter!})}</div>)}</div></section><aside><div className="side-card"><div className="eyebrow">ПОЛЕВЫЕ ЗАМЕТКИ</div><h3>Оставь себе подсказку</h3><label className="sr-only" htmlFor="notes">Заметки текущего прохождения</label><Textarea id="notes" maxLength={10000} value={run.notes} onChange={e=>updateRun({notes:e.target.value})} placeholder="Где остановился, какую книгу проверить, к кому вернуться…" className="notes-input"/><p className="micro-copy">Заметки входят в экспорт и контрольные точки.</p></div><div className="note-card"><h3>Возвращаешься к сохранению?</h3><p>Верни счётчик к состоянию выбранного сохранения. Сбор книг из разных веток не суммируется.</p><Button variant="ghost" className="text-action" onClick={()=>setModal('snapshots')}><RotateCcw/>Контрольные точки</Button></div></aside></div>}
<footer><span>НЕОФИЦИАЛЬНЫЙ ПОМОЩНИК · MVP 01</span><a href={sources.steam} target="_blank" rel="noreferrer">ДОСТИЖЕНИЯ В STEAM ↗</a></footer>
</main></div>
<Dialog open={modal!==null} onOpenChange={v=>{if(!v)setModal(null)}}><DialogContent className="tracker-dialog"><DialogTitle>{modal==='stage'?'Где ты сейчас?':modal==='decisions'?'Решения в этой ветке':modal==='snapshots'?'Контрольные точки':'Мой прогресс'}</DialogTitle><DialogDescription>{modal==='stage'?'Выбери текущий этап. Смена этапа не отмечает достижения и не меняет решения.':modal==='decisions'?'Отмечай фактические решения в текущем сохранении игры.':modal==='snapshots'?'Сохрани состояние трекера рядом с игровым сохранением. Саму игру сохраняй отдельно.':'Прогресс хранится локально в этом браузере. Экспортируй копию перед переносом на другое устройство.'}</DialogDescription>
{modal==='stage'&&<><div className="stage-choices">{stages.map(s=><button key={s.id} onClick={()=>setStageTarget(s.id)} className={stageTarget===s.id?'selected':''}><span>{s.mission}</span><strong>{s.short}</strong>{stageTarget===s.id&&<Check size={15}/>}</button>)}</div><div className="dialog-actions"><Button onClick={()=>changeStage(stageTarget)}>Я на этом этапе <ArrowRight/></Button></div></>}
{modal==='decisions'&&<div className="decision-form">{(state.spoilers?decisions:applicableDecisions).map(d=><div className="decision-field" key={d.id}><label>{d.title}</label><Pick label={d.title} value={run.decisions[d.id]||'unknown'} options={[{value:'unknown',label:'Ещё не отмечено'},...d.options]} onChange={v=>{const next={...run.decisions};if(v==='unknown')delete next[d.id];else next[d.id]=v;updateRun({decisions:next})}}/><p>{d.note}</p></div>)}{!applicableDecisions.length&&!state.spoilers&&<p>На этом этапе ещё нет решений для журнала. Поздние решения скрыты до нужного этапа.</p>}</div>}
{modal==='progress'&&<><div className="decision-field"><label>Режим основной кампании</label><Pick label="Сложность прохождения" value={run.difficulty} options={[{value:'normal',label:'Обычное прохождение'},{value:'ngplus',label:'Новая игра+'},{value:'permadeath',label:'Я никого об этом не просил'}]} onChange={v=>updateRun({difficulty:v as Run['difficulty']})}/><p>Режим с одной жизнью доступен после первого завершения игры.</p></div><div className="transfer-actions"><Button variant="outline" onClick={exportProgress}><Download/>Экспортировать</Button><Button variant="outline" onClick={()=>importInput.current?.click()}><Upload/>Импортировать</Button></div><div className="data-summary"><HardDrive size={17}/><span>{state.earned.length} достижений · {state.snapshots.length} контрольных точек</span></div><div className="reset-section"><h3>Начать новое прохождение</h3><p>Полученные достижения останутся. Этап, решения, книги, счётчики и заметки текущего прохождения сбросятся. Контрольные точки сохранятся.</p><Button variant="outline" onClick={()=>setConfirm({title:'Начать новое прохождение?',body:'Сначала сохрани контрольную точку, если хочешь вернуться к текущему маршруту. Уже полученные достижения останутся.',action:()=>{setState(s=>({...s,run:freshRun()}));setStorageSafe(true);setModal(null);setView('now');setNotice('Новое прохождение начато. Полученные достижения сохранены.')}})}><RotateCcw/>Новое прохождение</Button></div></>}
{modal==='snapshots'&&<><div className="save-row"><Input value={snapshotName} maxLength={100} onChange={e=>setSnapshotName(e.target.value)} placeholder={'Например: '+stage.short+' — до выбора'} aria-label="Название контрольной точки"/><Button onClick={saveSnapshot} disabled={state.snapshots.length>=12}><Save/>Сохранить</Button></div><p className="micro-copy">{state.snapshots.length} / 12 точек. Восстановление не снимает уже полученные достижения.</p><div className="snapshot-list">{state.snapshots.length?state.snapshots.map(s=><div className="snapshot" key={s.id}><div><h3>{s.name}</h3><p>{stages.find(x=>x.id===s.run.stage)?.short} · {s.run.books} книг · {new Date(s.createdAt).toLocaleDateString('ru-RU')}</p></div><Button variant="outline" size="icon" aria-label={'Восстановить '+s.name} onClick={()=>setConfirm({title:'Вернуться к «'+s.name+'»?',body:'Этап, решения, условия, счётчики и заметки заменятся сохранёнными. Достижения останутся полученными.',action:()=>{updateRun(structuredClone(s.run));setNotice('Контрольная точка восстановлена.');setModal(null)}})}><RotateCcw/></Button><Button variant="ghost" size="icon" aria-label={'Удалить '+s.name} onClick={()=>setConfirm({title:'Удалить контрольную точку?',body:s.name,action:()=>setState(x=>({...x,snapshots:x.snapshots.filter(v=>v.id!==s.id)}))})}><Trash2/></Button></div>):<div className="empty-state compact"><Save/><h3>Пока нет точек</h3><p>Первая пригодится перед развилкой или отъездом.</p></div>}</div></>}
</DialogContent></Dialog>
<Dialog open={detail!==null} onOpenChange={v=>{if(!v)setDetail(null)}}><DialogContent className="tracker-dialog achievement-dialog">{detail&&<><div className="detail-symbol"><Trophy/></div><span className="eyebrow">{detail.category} · {groups[detail.group]}</span><DialogTitle>{isHidden(detail)?'Скрытое достижение':detail.name}</DialogTitle><DialogDescription>{isHidden(detail)?'Это достижение относится к более позднему этапу. Включи спойлеры, чтобы прочитать подробности.':detail.description}</DialogDescription>{isHidden(detail)?<Button variant="outline" onClick={()=>setState(s=>({...s,spoilers:true}))}><Eye/>Открыть спойлеры</Button>:<><div className="instruction"><span className="eyebrow">ЧТО ДЕЛАТЬ</span><p>{detail.tip}</p></div>{status(detail,state).detail&&<div className="book-warning"><Info size={17}/><p>{status(detail,state).detail}</p></div>}<div className="detail-meta"><span>Когда</span><strong>{detail.stages.length>2?'По ходу основной кампании':detail.stages.map(id=>stages.find(s=>s.id===id)?.short).join(' / ')}</strong></div><div className="detail-actions"><Button onClick={()=>mark(detail.id,!state.earned.includes(detail.id))}>{state.earned.includes(detail.id)?<RotateCcw/>:<Check/>}{state.earned.includes(detail.id)?'Снять отметку':'Получено'}</Button><a href={sources.guide} target="_blank" rel="noreferrer">Открыть руководство <ExternalLink size={13}/></a></div></>}</>}</DialogContent></Dialog>
<Dialog open={confirm!==null} onOpenChange={v=>{if(!v)setConfirm(null)}}><DialogContent className="tracker-dialog confirm-dialog"><DialogTitle>{confirm?.title}</DialogTitle><DialogDescription>{confirm?.body}</DialogDescription><div className="dialog-actions"><Button variant="outline" onClick={()=>setConfirm(null)}>Отмена</Button><Button onClick={()=>{confirm?.action();setConfirm(null)}}>Подтвердить</Button></div></DialogContent></Dialog>
<input ref={importInput} type="file" accept=".json,application/json" className="sr-only" tabIndex={-1} aria-label="Файл прогресса" onChange={e=>void importProgress(e.target.files?.[0])}/>
{notice&&<div className="toast" role="status"><Info size={16}/>{notice}</div>}
</div>;
}