'use client';
import {sitePath} from '@/lib/site-path';
import {useEffect,useMemo,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Trophy,Crosshair,Box,BookOpen,Shield,ArrowRight,Check,Search,Download,Upload,Save,RotateCcw,GitBranch,ChevronRight,Info,Eye,EyeOff,Settings2,Plus,Minus,CheckCheck,Flag,HardDrive,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import {Breadcrumb,BreadcrumbList,BreadcrumbItem,BreadcrumbLink,BreadcrumbSeparator} from '@/components/ui/breadcrumb';
import {PanelLeftClose,PanelLeftOpen} from 'lucide-react';
import TrackerProgressSummary from '@/components/tracker-progress-summary';
import TrackerSourcesDialog from '@/components/tracker-sources-dialog';
import DeusExMap from '@/components/deus-ex-map';
import {Checkbox} from '@/components/ui/checkbox';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type Achievement,type StageId} from '@/lib/tracker-data';
import {bookGoals,type BookGoal} from '@/lib/book-goals';
import {createTranslator,dateLocales,languageKey,languageOptions,localizedCatalog,parseLocale,type Locale} from '@/lib/i18n';
import {beforeLeaving,flagAchievements,stageRecommendations} from '@/lib/tracker-recommendations';
import {freshRun,freshState,parseState,runStatus,setBookCollected,setEarned,setRunProgress,storageKey,type FlagId,type Run,type TrackerState} from '@/lib/tracker-state';

type View='now'|'all'|'map'|'collection';
type Modal='stage'|'decisions'|'progress'|'snapshots'|null;
type Confirmation={title:string;body:string;action:()=>void};
type ModelTool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
type ModelContext={registerTool:(tool:ModelTool,options:{signal:AbortSignal})=>void|Promise<void>};
const flagLabels:Record<FlagId,{title:string;good:string;bad:string}>={kills:{title:'Пацифист',good:'Убийств не было',bad:'Было убийство'},alarms:{title:'Проныра',good:'Тревог не было',bad:'Была тревога'},systemKills:{title:'Чисто, чисто, чисто, чисто!',good:'Убийств не было',bad:'Было убийство'},criminalKills:{title:'Все по правилам',good:'Убийств не было',bad:'Было убийство'},drugs:{title:'Без допинга',good:'Ничего не использовал',bad:'Использовал таблетку / батарею'}};
function Pick({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){
return <Select value={value} onValueChange={v=>{if(v!==null)onChange(v)}}><SelectTrigger aria-label={label} className="pick"><SelectValue>{options.find(o=>o.value===value)?.label||label}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;
}
const pad=(n:number)=>String(n).padStart(2,'0');
export default function Home(){
const [locale,setLocale]=useState<Locale>('ru');
const localeRef=useRef(locale);localeRef.current=locale;
const t=useMemo(()=>createTranslator(locale),[locale]);
const {achievements,decisions,groups,sources,stages}=useMemo(()=>localizedCatalog(locale),[locale]);
const [state,setState]=useState<TrackerState>(freshState);
const stateRef=useRef(state);stateRef.current=state;
const [ready,setReady]=useState(false),[storageSafe,setStorageSafe]=useState(true),[storageError,setStorageError]=useState('');
const [view,setView]=useState<View>('now'),[modal,setModal]=useState<Modal>(null),[detailId,setDetailId]=useState<string|null>(null),[confirm,setConfirm]=useState<Confirmation|null>(null);
const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[group,setGroup]=useState('all'),[notice,setNotice]=useState(''),[stageTarget,setStageTarget]=useState<StageId>('dubai'),[snapshotName,setSnapshotName]=useState('');
const [hoveredStage,setHoveredStage]=useState<StageId|null>(null);
const [sidebarCollapsed,setSidebarCollapsed]=useState(false),[sidebarReady,setSidebarReady]=useState(false),[isMobile,setIsMobile]=useState(false);
useEffect(()=>{try{setSidebarCollapsed(localStorage.getItem('dx-achievement-protocol-sidebar-collapsed')==='true')}catch{}setSidebarReady(true);const media=window.matchMedia('(max-width:640px)');const sync=()=>setIsMobile(media.matches);sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync)},[]);
useEffect(()=>{if(sidebarReady)try{localStorage.setItem('dx-achievement-protocol-sidebar-collapsed',String(sidebarCollapsed))}catch{}},[sidebarCollapsed,sidebarReady]);
const importInput=useRef<HTMLInputElement>(null);
const detail=achievements.find(a=>a.id===detailId)||null;
useEffect(()=>{try{const saved=parseLocale(localStorage.getItem(languageKey));if(saved)setLocale(saved)}catch{}},[]);
useEffect(()=>{document.documentElement.lang=locale;const meta=document.querySelector('meta[name="description"]');meta?.setAttribute('content',t('Личный трекер достижений Mankind Divided. Этапы, решения и прогресс прохождения.'));if(ready)try{localStorage.setItem(languageKey,locale)}catch{setNotice('Язык изменён. Не удалось сохранить настройку в браузере.')}},[locale,ready,t]);
function changeLanguage(value:string){const next=parseLocale(value);if(next)setLocale(next)}
useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw)setState(parseState(JSON.parse(raw)));}catch{setStorageSafe(false);setStorageError('Не удалось прочитать сохранение. Оно не перезаписано. Можно импортировать резервную копию.');}setReady(true)},[]);
useEffect(()=>{if(!ready||!storageSafe)return;try{localStorage.setItem(storageKey,JSON.stringify(state));setStorageError('')}catch{setStorageError('Не удалось сохранить в браузере. Экспортируй прогресс в файл.')}},[state,ready,storageSafe]);
useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice]);
useEffect(()=>{
const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;
const lifecycle=new AbortController();
const read=()=>({language:localeRef.current,stage:stateRef.current.run.stage,earned:stateRef.current.earned,total:achievements.length,books:stateRef.current.run.books,collectedBookIds:stateRef.current.run.collectedBooks,recommended:stageRecommendations(stateRef.current).pending.map(a=>a.id),completedStages:stateRef.current.run.completedStages});
for(const tool of [
{name:'get_tracker_progress',title:t("Прочитать прогресс"),description:'Read manually recorded achievements and the current game stage. Does not access the game or Steam.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>read()},
{name:'set_achievements',title:t("Отметить достижения"),description:'Manually mark a batch of achievement IDs as earned or not earned. Does not change current stage, completed stages, story decisions or run conditions.',inputSchema:{type:'object',properties:{ids:{type:'array',items:{type:'string'}},earned:{type:'boolean'}},required:['ids','earned'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{
if(!input||typeof input!=='object')throw Error('Expected an object');const v=input as {ids?:unknown;earned?:unknown};
if(!Array.isArray(v.ids)||!v.ids.every(id=>typeof id==='string'&&achievements.some(a=>a.id===id))||typeof v.earned!=='boolean')throw Error('Invalid achievement IDs or earned flag');
const ids=v.ids as string[];flushSync(()=>setState(s=>setEarned(s,ids,v.earned as boolean)));return read();
}},
{name:'set_playthrough_progress',title:t("Отметить прохождение"),description:'Manually mark stage IDs complete in this playthrough. Never changes earned achievements or selects the current stage.',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['stages']},ids:{type:'array',items:{type:'string'}},completed:{type:'boolean'}},required:['kind','ids','completed'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{
if(!input||typeof input!=='object')throw Error('Expected an object');const v=input as {kind?:unknown;ids?:unknown;completed?:unknown};
if(v.kind!=='stages'||!Array.isArray(v.ids)||!v.ids.every(id=>typeof id==='string'&&stages.some(x=>x.id===id))||typeof v.completed!=='boolean')throw Error('Invalid playthrough IDs or completed flag');
flushSync(()=>setState(s=>setRunProgress(s,'stages',v.ids as string[],v.completed as boolean)));return read();
}},
{name:'set_tracker_language',title:t('Язык интерфейса'),description:'Change only the interface language. Accepts uk (UA), ru or en. Preserves all achievement, playthrough, note and checkpoint data.',inputSchema:{type:'object',properties:{language:{type:'string',enum:['uk','ru','en']}},required:['language'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const next=input&&typeof input==='object'?parseLocale((input as {language?:unknown}).language):null;if(!next)throw Error('Invalid language');flushSync(()=>setLocale(next));return read()}}
] satisfies ModelTool[]){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}
return()=>lifecycle.abort();
},[t]);
const run=state.run,stage=stages.find(s=>s.id===run.stage)!,stageIndex=stages.findIndex(s=>s.id===run.stage);
const {eligible,focused,flexible,earnedHere}=stageRecommendations(state,achievements);
const campaignStages=stages.filter(s=>s.group==='campaign');
const completedCampaign=campaignStages.filter(s=>run.completedStages.includes(s.id)).length;
const currentBooks=bookGoals.filter(book=>book.stage===run.stage);
const pendingCurrentBooks=currentBooks.filter(book=>!run.collectedBooks.includes(book.id));
const collectionStages=stages.filter(s=>bookGoals.some(book=>book.stage===s.id));
const booksAchievementEarned=state.earned.includes('tablets');
const nowCount=focused.length+(booksAchievementEarned?0:pendingCurrentBooks.length);
const currentWarnings=focused.flatMap(achievement=>(achievement.warnings||[]).map((warning,index)=>({id:`${achievement.id}-${index}`,achievement:achievement.name,warning})));
const hoveredStageInfo=hoveredStage?stages.find(item=>item.id===hoveredStage):null;
const stageFork=(id:StageId)=>id==='prague1'?t("Калибратор: до встречи или после просьбы"):id==='prague2'?t("Развилка: Элисон или банк"):id==='london'?(state.spoilers||stageIndex>=6?t("Финал: нелетально или устройство"):t("В финале есть важное решение")):'';
function updateRun(patch:Partial<Run>){setState(s=>({...s,run:{...s.run,...patch}}))}
function mark(id:string,value:boolean){setState(s=>setEarned(s,[id],value))}
function markBook(id:string,value:boolean){setState(s=>setBookCollected(s,[id],value))}
function markRun(kind:'stages',id:string,value:boolean){setState(s=>setRunProgress(s,kind,[id],value))}
function changeStage(id:StageId){updateRun({stage:id});setModal(null);setView('now');setNotice('Этап обновлён. Достижения и решения сохранены.')}
function openStage(){setStageTarget(run.stage);setModal('stage')}
function setCounter(id:string,value:number,max:number){const n=Math.max(0,Math.min(max,Math.trunc(Number.isFinite(value)?value:0)));updateRun({counters:{...run.counters,[id]:n}})}
function exportProgress(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='deus-ex-progress-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Копия прогресса сохранена в файл.')}
async function importProgress(file:File|undefined){if(!file)return;try{if(file.size>2000000)throw Error(t("Файл слишком большой."));const next=parseState(JSON.parse(await file.text()));setConfirm({title:t("Загрузить прогресс из файла?"),body:t("Текущие отметки, решения и контрольные точки будут заменены. При необходимости сначала экспортируй текущий прогресс."),action:()=>{setState(next);setStorageSafe(true);setModal(null);setNotice('Прогресс восстановлен.')}})}catch(e){setNotice(e instanceof SyntaxError?t("Не удалось прочитать файл."):e instanceof Error?e.message:t("Не удалось прочитать файл."))}finally{if(importInput.current)importInput.current.value=''}}
function saveSnapshot(){if(state.snapshots.length>=12){setNotice('Сохранено 12 точек. Удали ненужную, чтобы добавить новую.');return}const name=snapshotName.trim()||stage.short+' · '+new Date().toLocaleDateString(dateLocales[locale]);setState(s=>({...s,snapshots:[{id:crypto.randomUUID(),name,createdAt:new Date().toISOString(),run:structuredClone(s.run)},...s.snapshots]}));setSnapshotName('');setNotice('Состояние трекера сохранено. Сохранение игры сделай отдельно.')}
function isHidden(a:Achievement){return !!a.secret&&!state.spoilers&&!state.earned.includes(a.id)&&(a.group!==stage.group||Math.min(...a.stages.map(id=>stages.findIndex(s=>s.id===id)))>stageIndex)}
function Counter({id,label,value,max}:{id:string;label:string;value:number;max:number}){return <div className="counter"><Button variant="outline" size="icon" aria-label={t("Уменьшить: ")+label} disabled={!value} onClick={()=>setCounter(id,value-1,max)}><Minus/></Button><Input aria-label={label} type="number" min={0} max={max} value={value} onChange={e=>setCounter(id,Number(e.target.value),max)}/><span>/ {max}</span><Button variant="outline" size="icon" aria-label={t("Увеличить: ")+label} disabled={value>=max} onClick={()=>setCounter(id,value+1,max)}><Plus/></Button></div>}
function AchievementMarks(a:Achievement){const name=isHidden(a)?t("скрытое достижение ")+a.id:a.name;return <div className="achievement-checks" role="group" aria-label={t("Отметки: ")+name}><label><Checkbox aria-label={t("Достижение получено: ")+name} checked={state.earned.includes(a.id)} onCheckedChange={v=>mark(a.id,v)}/><span>{t("Достижение получено")}<small>{t("В любом прохождении")}</small></span></label></div>}
function Item({a}:{a:Achievement}){const s=runStatus(a,state),hidden=isHidden(a),done=state.earned.includes(a.id);return <article key={a.id} className={'achievement '+(done?'is-done':'')}><div className="achievement-icon">{done?<Check/>:a.kind==='collect'?<BookOpen/>:a.kind==='combat'?<Crosshair/>:a.kind==='run'?<Shield/>:<Trophy/>}</div><div className="achievement-body"><span className="eyebrow">{a.category} · {a.stages.length>2?t("ПО ХОДУ ИГРЫ"):a.stages.map(id=>stages.find(s=>s.id===id)?.short).join(' / ')}</span><button className="title-button" onClick={()=>setDetailId(a.id)}><h3>{hidden?t("Скрытое достижение"):a.name}<ChevronRight size={13}/></h3></button><p>{hidden?t("Описание откроется на соответствующем этапе."):a.description}</p><span className={'tag '+s.tone}>{t(s.label)}</span>{!hidden&&a.steps?.length&&<span className="tag long">{a.steps.length} {t("ШАГОВ")}</span>}{a.kind==='combat'&&run.goals.some(id=>!state.earned.includes(id))&&!done&&<span className="tag neutral">{t("Сохранись перед попыткой")}</span>}{s.detail&&!hidden&&<p className="blocker">{t(s.detail)}</p>}</div>{AchievementMarks(a)}</article>}
function BookItem({book}:{book:BookGoal}){const done=run.collectedBooks.includes(book.id),name=locale==='en'?book.titleEn:`${book.title} (${book.titleEn})`,requirement=book.number===11?t("ТРЕБУЕТ SM02 «КУЛЬТ ЛИЧНОСТИ»"):book.number===50?t("НУЖНА КЛЮЧ-КАРТА РУКЕРА"):[54,56,57,58].includes(book.number)?t("ТОЛЬКО ВТОРОЕ ПОСЕЩЕНИЕ ПРАГИ"):book.number===64?t("ТРЕБУЕТ M12 «ОГРАБЛЕНИЕ»"):[65,66,67].includes(book.number)?t("M11 ИЛИ ПОСЛЕ ОГРАБЛЕНИЯ"):book.number>=71&&book.number<=72?t("ТРЕБУЕТ «ПОСЛЕДНЕГО УРОЖАЯ»"):'';return <article className={'book-goal '+(done?'is-done':'')} key={book.id}><label className="book-goal-mark"><Checkbox aria-label={t("Книга собрана: ")+name} checked={done} onCheckedChange={value=>markBook(book.id,value)}/><span>#{pad(book.number)}</span></label><details><summary><span><strong>{name}</strong><small lang={locale==='ru'?undefined:'ru'}>{book.location}</small></span><ChevronRight size={14}/></summary><p lang={locale==='ru'?undefined:'ru'}>{book.hint}</p>{requirement&&<span className="tag blocked">{requirement}</span>}</details></article>}
function FlagControl({id}:{id:FlagId}){const raw=flagLabels[id],f={title:t(raw.title),good:t(raw.good),bad:t(raw.bad)};return <div className="flag-control" key={id}><label>{f.title}</label><Pick label={f.title} value={run.flags[id]} options={[{value:'unknown',label:t("Не уверен / не отмечено")},{value:'clear',label:f.good},{value:'broken',label:f.bad}]} onChange={v=>updateRun({flags:{...run.flags,[id]:v as Run['flags'][FlagId]}})}/><span className={'flag-hint '+run.flags[id]}>{run.flags[id]==='clear'?t("По твоим отметкам условие сохранено"):run.flags[id]==='broken'?t("Нужен откат или другое прохождение"):t("Подтверди состояние вручную")}</span></div>}
function SidePanel(){
const keys:FlagId[]=(stage.group==='campaign'?['kills','alarms']:stage.group==='system'?['systemKills']:stage.group==='criminal'?['criminalKills','drugs']:[] as FlagId[]).filter(id=>!state.earned.includes(flagAchievements[id as FlagId])) as FlagId[];
const goals=[['pacifist',t("Без убийств")],['fox',t("Без тревог")]].filter(([id])=>!state.earned.includes(id));
const reminders=beforeLeaving(state);
return <aside>{keys.length>0&&<div className="side-card"><div className="eyebrow"><Shield size={15}/>{t("НА ВСЁ ПРОХОЖДЕНИЕ")}</div><h3>{stage.group==='campaign'?t("Чистая работа"):groups[stage.group]}</h3><p>{t("Обновляй условия после важных событий.")}</p>{keys.map(id=>FlagControl({id}))}{stage.group==='campaign'&&goals.length>0&&<div className="goals"><span className="eyebrow">{t("МОИ ЦЕЛИ")}</span>{goals.map(([id,label])=><label key={id}><Checkbox checked={run.goals.includes(id)} onCheckedChange={v=>updateRun({goals:v?[...run.goals,id]:run.goals.filter(x=>x!==id)})}/>{label}</label>)}</div>}</div>}{reminders.length>0&&<div className="note-card"><span className="eyebrow"><Flag size={13}/>{t("ПЕРЕД УХОДОМ")}</span><h3>{t("Проверь, прежде чем идти дальше")}</h3>{reminders.map(text=><p key={text}>{t(text)}</p>)}<Button variant="ghost" className="text-action save-checkpoint" onClick={()=>setModal('snapshots')}><Save size={13}/>{t(" Сохранить точку")}</Button></div>}</aside>}
const filtered=achievements.filter(a=>(group==='all'||a.group===group)&&(filter==='all'||(filter==='earned'?state.earned.includes(a.id):filter==='now'?runStatus(a,state).tone==='now':!state.earned.includes(a.id)))&&(!search.trim()||(!isHidden(a)&&(a.name+' '+a.description).toLocaleLowerCase(locale).includes(search.trim().toLocaleLowerCase(locale)))));
const applicableDecisions=decisions.filter(d=>stage.group==='campaign'&&stages.findIndex(s=>s.id===d.stage)<=stageIndex);
return <div className={"app-shell dx-shell"+(sidebarCollapsed?" sidebar-collapsed":"")} aria-busy={!ready}>
<aside id="dx-sidebar" className="sidebar"><Button variant="ghost" size="icon" className="sidebar-toggle" onClick={()=>setSidebarCollapsed(value=>!value)} aria-expanded={!sidebarCollapsed} aria-controls="dx-sidebar" aria-label={sidebarCollapsed?t("Развернуть боковую панель"):t("Свернуть боковую панель")} title={sidebarCollapsed?t("Развернуть боковую панель"):t("Свернуть боковую панель")}>{sidebarCollapsed?<PanelLeftOpen size={17}/>:<PanelLeftClose size={17}/>}</Button><a href={sitePath('/deus-ex')} className="brand" aria-label="Deus Ex Achievement Protocol"><span className="brand-symbol">DX</span><span className="sidebar-brand-copy">DEUS EX<small>ACHIEVEMENT PROTOCOL</small></span></a><div className="sidebar-label">{t("ЛИЧНОЕ ДОСЬЕ / 01")}</div><nav aria-label={t("Разделы трекера")}>{([{id:'now',label:t("Сейчас"),icon:Crosshair,count:nowCount},{id:'all',label:t("Достижения"),icon:Trophy,count:81},{id:'map',label:t("Карта 3D"),icon:Box},{id:'collection',label:t("Коллекция"),icon:BookOpen}] as const).map(n=><Button key={n.id} variant="ghost" className={'nav-item '+(view===n.id?'active':'')} onClick={()=>setView(n.id)} aria-label={n.label} title={n.label+('count'in n?' · '+n.count:'')} aria-current={view===n.id?'page':undefined}><n.icon/><span className="nav-label">{n.label}</span>{'count'in n&&<span className="nav-count">{pad(n.count)}</span>}</Button>)}</nav><div className="sidebar-secondary"><Button variant="ghost" className="nav-item" onClick={()=>setModal('snapshots')} aria-label={t("Контрольные точки")} title={t("Контрольные точки")}><Save/><span className="nav-label">{t("Контрольные точки")}</span></Button><Button variant="ghost" className="nav-item" onClick={()=>setModal('progress')} aria-label={t("Мой прогресс")} title={t("Мой прогресс")}><Settings2/><span className="nav-label">{t("Мой прогресс")}</span></Button></div><div className="language-picker"><span className="eyebrow">{t('Язык интерфейса')}</span><Pick label={t('Язык интерфейса')} value={locale} options={sidebarCollapsed&&!isMobile?languageOptions.map(option=>({...option,label:option.value==='uk'?'UA':option.value.toUpperCase()})):languageOptions} onChange={changeLanguage}/></div></aside>
<div className="workspace"><header className="topbar"><div className="topbar-navigation"><Breadcrumb className="tracker-breadcrumb" aria-label={t("Навигация по сайту")}><BreadcrumbList><BreadcrumbItem><BreadcrumbLink href={sitePath('/')}>{t("Главная")}</BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator>{'>'}</BreadcrumbSeparator><BreadcrumbItem><BreadcrumbLink href={sitePath('/deus-ex')} aria-current="page" onClick={event=>{if(!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&!event.altKey){event.preventDefault();setView('now')}}}>Deus Ex: Mankind Divided</BreadcrumbLink></BreadcrumbItem></BreadcrumbList></Breadcrumb></div><div className="top-actions"><button className="spoiler-toggle" onClick={()=>setState(s=>({...s,spoilers:!s.spoilers}))} aria-label={state.spoilers?t("Скрыть будущие спойлеры"):t("Показать будущие спойлеры")} title={state.spoilers?t("Скрыть будущие спойлеры"):t("Показать будущие спойлеры")} aria-pressed={state.spoilers}>{state.spoilers?<Eye size={15}/>:<EyeOff size={15}/>}<span>{state.spoilers?t("Спойлеры открыты"):t("Без будущих спойлеров")}</span></button><Button variant="ghost" size="sm" className="top-save" onClick={exportProgress}><Download size={12}/>{t(" Экспорт")}</Button></div></header>
<main>{storageError&&<div className="storage-warning" role="alert"><Info size={16}/>{t(storageError)}<Button variant="outline" onClick={()=>setModal('progress')}>{t("Мой прогресс")}</Button></div>}
<h1 className="sr-only">{view==='now'?t("Текущий этап прохождения"):view==='all'?t("Достижения"):view==='map'?t("Карта 3D"):t("Коллекция")}</h1>
{view!=='map'&&<>
<div className="stage-rail-shell" onMouseLeave={()=>setHoveredStage(null)}>
<ol className="stage-rail" aria-label={t("Маршрут прохождения")}>{stages.map((s,index)=>{const related=achievements.filter(a=>a.stages.includes(s.id)&&a.stages.length<=2),earned=state.earned.filter(id=>related.some(a=>a.id===id)).length;return <li key={s.id}><button type="button" className="stage-rail-node" data-complete={run.completedStages.includes(s.id)||undefined} aria-current={run.stage===s.id?'step':undefined} aria-describedby={hoveredStage===s.id?`stage-preview-${s.id}`:undefined} aria-label={`${pad(index+1)} · ${s.name} · ${earned} / ${related.length} ${t("достижений получено")}`} onMouseEnter={()=>setHoveredStage(s.id)} onFocus={()=>setHoveredStage(s.id)} onBlur={()=>setHoveredStage(null)} onClick={()=>changeStage(s.id)}>{pad(index+1)}</button></li>})}</ol>
{hoveredStageInfo&&(()=>{const related=achievements.filter(a=>a.stages.includes(hoveredStageInfo.id)&&a.stages.length<=2),earned=state.earned.filter(id=>related.some(a=>a.id===id)).length,fork=stageFork(hoveredStageInfo.id);return <div className="stage-rail-preview" role="tooltip" id={`stage-preview-${hoveredStageInfo.id}`}><div><small>{hoveredStageInfo.mission}</small><strong>{hoveredStageInfo.name}</strong><span>{hoveredStageInfo.subtitle}</span></div><div className="stage-rail-preview-meta"><b>{earned} / {related.length}</b><span>{t("достижений получено")}</span>{run.stage===hoveredStageInfo.id&&<em>{t("ТЫ ЗДЕСЬ")}</em>}{run.completedStages.includes(hoveredStageInfo.id)&&<em>{t("Этап пройден")}</em>}</div>{fork&&<p><GitBranch size={12}/>{fork}</p>}</div>})()}
</div>
<section className="mission-banner"><div className="mission-number" key={'number-'+stage.id}>{pad(stageIndex+1)}</div><div className="mission-copy" key={stage.id}><div className="eyebrow">{t("ТЕКУЩИЙ ЭТАП · ")}{stage.mission}</div><h2>{stage.name}</h2><p>{stage.subtitle}</p></div><Button variant="outline" onClick={openStage}>{t("Изменить этап ")}<ArrowRight/></Button></section>
<div className="run-progress-strip"><label><Checkbox aria-label={t("Этап пройден: ")+stage.short} checked={run.completedStages.includes(run.stage)} onCheckedChange={v=>markRun('stages',run.stage,v)}/><span>{t("Этот этап пройден")}</span></label><p>{t("Отметки этапов не меняют полученные достижения.")}</p></div>
<TrackerProgressSummary label={t("Прогресс достижений и прохождения")} metrics={[{label:t("Получено достижений"),value:state.earned.length,max:81},{label:t("Пройдено этапов кампании"),value:completedCampaign,max:campaignStages.length},{label:t("Получено достижений этапа"),value:earnedHere,max:eligible.length}]}/>
</>}
{view==='now'&&<div className="content-grid"><section>
{currentWarnings.length>0&&<section className="stage-warnings" aria-labelledby="stage-warnings-title"><div className="stage-warnings-heading" id="stage-warnings-title"><Info size={15}/><span>{t("ВАЖНО НЕ ПРОПУСТИТЬ")}</span></div><div className="stage-warning-list">{currentWarnings.map(item=><article className="stage-warning" key={item.id}><Info size={16}/><div><strong>{item.achievement}</strong><p>{item.warning}</p></div></article>)}</div></section>}
<div className="section-heading"><h2>{t("Сделать сейчас")}</h2><span>{pad(nowCount)}{t(" ОСТАЛОСЬ")}</span></div>
{focused.length>0?<div className="achievement-list">{focused.map(a=>Item({a}))}</div>:<div className="empty-state"><CheckCheck/><h3>{flexible.length?t("Проверь общие задачи"):t("Всё на этом этапе уже получено")}</h3><p>{flexible.length?t("На этом этапе доступны задачи, которые можно выполнить по ходу игры."):t("Полученные достижения доступны в общем списке. Можно продолжать прохождение.")}</p></div>}
{flexible.length>0&&<details className="flexible"><summary>{t("Также можно выполнить по ходу игры ")}<span>{flexible.length}</span></summary><div className="achievement-list">{flexible.map(a=>Item({a}))}</div></details>}
{currentBooks.length>0&&!booksAchievementEarned&&<section className="stage-book-goals"><div className="section-heading"><h2>{t("Книги на этом этапе")}</h2><span>{currentBooks.length-pendingCurrentBooks.length} / {currentBooks.length}</span></div><div className="book-goal-list">{currentBooks.map(book=>BookItem({book}))}</div></section>}
{stage.group==='campaign'&&applicableDecisions.length>0&&<div className="decision-callout"><GitBranch/><div><h3>{t("У каждого решения есть последствия")}</h3><p>{t("Обнови журнал, чтобы видеть закрытые варианты.")}</p></div><Button variant="outline" onClick={()=>setModal('decisions')}>{t("Мои решения")}</Button></div>}
<div className="next-stage"><span>{stage.group==='campaign'?t("Перед переходом проверь список справа."):t("Можно вернуться в любой режим.")}</span><Button variant="outline" onClick={()=>{setStageTarget(stages[Math.min(stageIndex+1,stages.length-1)].id);setModal('stage')}}>{t("Выбрать следующий этап ")}<ArrowRight/></Button></div>
</section>{SidePanel()}</div>}
{view==='all'&&<section>
<div className="section-heading"><h2>{filter==='earned'?t("Полученные достижения"):t("Список достижений")}</h2><span>{filtered.length} / 81</span></div>
<div className="filters"><div className="search-field"><Search size={17}/><Input placeholder={t("Поиск по названию или условию…")} aria-label={t("Поиск достижений")} value={search} onChange={e=>setSearch(e.target.value)}/></div><Pick label={t("Режим")} value={group} onChange={setGroup} options={[{value:'all',label:t("Все режимы")},...Object.entries(groups).map(([value,label])=>({value,label}))]}/><Pick label={t("Статус")} value={filter} onChange={setFilter} options={[{value:'todo',label:t("Не получены")},{value:'all',label:t("Все достижения")},{value:'earned',label:t("Получены")},{value:'now',label:t("Доступны сейчас")}]}/></div>
{filtered.length?<div className="achievement-list archive">{filtered.map(a=>Item({a}))}</div>:<div className="empty-state"><Search/><h3>{t("Ничего не найдено")}</h3><p>{t("Измени запрос или фильтры. Будущие секреты скрыты, пока выключены спойлеры.")}</p><Button variant="outline" onClick={()=>{setSearch('');setGroup('all');setFilter('all')}}>{t("Сбросить фильтры")}</Button></div>}
<p className="micro-copy">{t("«Закрыто выбором» относится к текущей ветке. Уже полученные достижения остаются в архиве.")}</p>
</section>}
{view==='map'&&<DeusExMap locale={locale} currentStage={run.stage}/>}
{view==='collection'&&<div className="content-grid"><section>
<div className="collection-panel"><div className="eyebrow"><BookOpen size={16}/>{t("КОЛЛЕКЦИОНЕР ПЛАНШЕТОВ")}</div><h2>{t("75 отдельных целей")}</h2><p>{t("Отмечай каждую найденную электронную книгу. Общий прогресс обновляется по этим отметкам.")}</p><div className="book-count"><strong>{run.books}<small>/ 75</small></strong><span>{Math.round(run.books/75*100)}%</span></div><Progress value={run.books/75*100} aria-label={t("Собрано книг")}/><p className="micro-copy">{t("75 / 75 не отмечает достижение автоматически. Проверь его получение и поставь галочку в списке.")}</p><div className="book-warning"><Info size={17}/><p>{t("Книги не переносятся в NG+. Для полного маршрута нужны «Культ личности», победа в споре с Рукером, банковская ветка и «Последний урожай».")}</p></div></div>
{booksAchievementEarned&&<div className="complete-note"><CheckCheck size={18}/>{t("Достижение за книги уже получено. Отметки книг сохранены отдельно.")}</div>}
<div className="section-heading journal-heading"><h2>{t("Маршрут электронных книг")}</h2><span>{run.books} / 75</span></div><div className="collection-stage-list">{collectionStages.map(s=>{const books=bookGoals.filter(book=>book.stage===s.id),done=books.filter(book=>run.collectedBooks.includes(book.id)).length;return <details className="book-stage" key={s.id}><summary><span><small>{s.mission}</small><strong>{s.name}</strong></span><em>{done} / {books.length}</em><ChevronRight size={15}/></summary><div className="book-goal-list">{books.map(book=>BookItem({book}))}</div></details>})}</div>
<div className="section-heading journal-heading"><h2>{t("Счётчики Breach")}</h2><span>{t("ВРУЧНУЮ")}</span></div><div className="counter-list">{achievements.filter(a=>a.group==='breach'&&a.counter&&a.counter>1&&!state.earned.includes(a.id)).map(a=><div className="counter-row" key={a.id}><div><h3>{a.name}</h3><p>{a.description}</p><Progress value={(run.counters[a.id]||0)/a.counter!*100} aria-label={a.name}/></div>{Counter({id:a.id,label:a.name,value:run.counters[a.id]||0,max:a.counter!})}</div>)}</div></section><aside><div className="side-card"><div className="eyebrow">{t("ПОЛЕВЫЕ ЗАМЕТКИ")}</div><h3>{t("Оставь себе подсказку")}</h3><label className="sr-only" htmlFor="notes">{t("Заметки текущего прохождения")}</label><Textarea id="notes" maxLength={10000} value={run.notes} onChange={e=>updateRun({notes:e.target.value})} placeholder={t("Где остановился, какую книгу проверить, к кому вернуться…")} className="notes-input"/><p className="micro-copy">{t("Заметки входят в экспорт и контрольные точки.")}</p></div><div className="note-card"><h3>{t("Возвращаешься к сохранению?")}</h3><p>{t("Верни отметки книг к состоянию выбранного сохранения. Сбор из разных веток не суммируется.")}</p><Button variant="ghost" className="text-action" onClick={()=>setModal('snapshots')}><RotateCcw/>{t("Контрольные точки")}</Button></div></aside></div>}
<footer><span>{t("НЕОФИЦИАЛЬНЫЙ ПОМОЩНИК · MVP 01")}</span><TrackerSourcesDialog locale={locale} theme="deus-ex" sources={[{url:sources.guide,title:t("Исходное руководство"),platform:"Steam Community"},{url:sources.walkthrough,title:t("Подробные маршруты заданий"),description:t("Пошаговые условия и точки провала многоэтапных достижений."),platform:"Gamer Guides"},{url:sources.roadmap,title:t("Развилки и прохождение"),platform:"PowerPyx"},{url:sources.steam,title:t("Достижения в Steam"),platform:"Steam"},{url:sources.booksGuide,title:t("Полный гайд по 75 электронным книгам"),description:t("Маршрут и расположение всех электронных книг."),platform:"Steam Community"},{url:sources.booksWiki,title:t("Deus Ex Wiki: все 75 электронных книг"),description:t("Помещения, этажи, ориентиры и условия доступа для каждой книги."),platform:"Deus Ex Wiki"},{url:sources.books,title:t("Видео: все 75 книг по порядку"),platform:"YouTube"}]}/></footer>
</main></div>
<Dialog open={modal!==null} onOpenChange={v=>{if(!v)setModal(null)}}><DialogContent closeLabel={t('Закрыть')} className="tracker-dialog"><DialogTitle>{modal==='stage'?t("Где ты сейчас?"):modal==='decisions'?t("Решения в этой ветке"):modal==='snapshots'?t("Контрольные точки"):t("Мой прогресс")}</DialogTitle><DialogDescription>{modal==='stage'?t("Выбери текущий этап. Смена этапа не отмечает его пройденным. Достижения и решения сохраняются."):modal==='decisions'?t("Отмечай фактические решения в текущем сохранении игры."):modal==='snapshots'?t("Сохрани состояние трекера рядом с игровым сохранением. Саму игру сохраняй отдельно."):t("Прогресс хранится локально в этом браузере. Экспортируй копию перед переносом на другое устройство.")}</DialogDescription>
{modal==='stage'&&<><div className="stage-choices">{stages.map(s=><button key={s.id} onClick={()=>setStageTarget(s.id)} className={stageTarget===s.id?'selected':''}><span>{s.mission}</span><strong>{s.short}</strong>{stageTarget===s.id&&<Check size={15}/>}</button>)}</div><div className="dialog-actions"><Button onClick={()=>changeStage(stageTarget)}>{t("Я на этом этапе ")}<ArrowRight/></Button></div></>}
{modal==='decisions'&&<div className="decision-form">{(state.spoilers?decisions:applicableDecisions).map(d=><div className="decision-field" key={d.id}><label>{d.title}</label><Pick label={d.title} value={run.decisions[d.id]||'unknown'} options={[{value:'unknown',label:t("Ещё не отмечено")},...d.options]} onChange={v=>{const next={...run.decisions};if(v==='unknown')delete next[d.id];else next[d.id]=v;updateRun({decisions:next})}}/><p>{d.note}</p></div>)}{!applicableDecisions.length&&!state.spoilers&&<p>{t("На этом этапе ещё нет решений для журнала. Поздние решения скрыты до нужного этапа.")}</p>}</div>}
{modal==='progress'&&<><div className="decision-field"><label>{t("Режим основной кампании")}</label><Pick label={t("Сложность прохождения")} value={run.difficulty} options={[{value:'normal',label:t("Обычное прохождение")},{value:'ngplus',label:t("Новая игра+")},{value:'permadeath',label:t("Я никого об этом не просил")}]} onChange={v=>updateRun({difficulty:v as Run['difficulty']})}/><p>{t("Режим с одной жизнью доступен после первого завершения игры.")}</p></div><div className="transfer-actions"><Button variant="outline" onClick={exportProgress}><Download/>{t("Экспортировать")}</Button><Button variant="outline" onClick={()=>importInput.current?.click()}><Upload/>{t("Импортировать")}</Button></div><div className="data-summary"><HardDrive size={17}/><span>{state.earned.length}{t(" достижений · ")}{run.completedStages.length}{t(" этапов пройдено · ")}{state.snapshots.length}{t(" контрольных точек")}</span></div><div className="reset-section"><h3>{t("Начать новое прохождение")}</h3><p>{t("Полученные достижения останутся. Этап, пройденные этапы, решения, книги, счётчики и заметки текущего прохождения сбросятся. Контрольные точки сохранятся.")}</p><Button variant="outline" onClick={()=>setConfirm({title:t("Начать новое прохождение?"),body:t("Сначала сохрани контрольную точку, если хочешь вернуться к текущему маршруту. Уже полученные достижения останутся."),action:()=>{setState(s=>({...s,run:freshRun()}));setStorageSafe(true);setModal(null);setView('now');setNotice('Новое прохождение начато. Полученные достижения сохранены.')}})}><RotateCcw/>{t("Новое прохождение")}</Button></div></>}
{modal==='snapshots'&&<><div className="save-row"><Input value={snapshotName} maxLength={100} onChange={e=>setSnapshotName(e.target.value)} placeholder={t("Например: ")+stage.short+t(" — до выбора")} aria-label={t("Название контрольной точки")}/><Button onClick={saveSnapshot} disabled={state.snapshots.length>=12}><Save/>{t("Сохранить")}</Button></div><p className="micro-copy">{state.snapshots.length}{t(" / 12 точек. Восстановление не снимает уже полученные достижения.")}</p><div className="snapshot-list">{state.snapshots.length?state.snapshots.map(s=><div className="snapshot" key={s.id}><div><h3>{s.name}</h3><p>{stages.find(x=>x.id===s.run.stage)?.short} · {s.run.books}{t(" книг · ")}{new Date(s.createdAt).toLocaleDateString(dateLocales[locale])}</p></div><Button variant="outline" size="icon" aria-label={t("Восстановить ")+s.name} onClick={()=>setConfirm({title:t("Вернуться к «")+s.name+'»?',body:t("Этап, пройденные этапы, решения, условия, счётчики и заметки заменятся сохранёнными. Достижения останутся полученными."),action:()=>{updateRun(structuredClone(s.run));setNotice('Контрольная точка восстановлена.');setModal(null)}})}><RotateCcw/></Button><Button variant="ghost" size="icon" aria-label={t("Удалить ")+s.name} onClick={()=>setConfirm({title:t("Удалить контрольную точку?"),body:s.name,action:()=>setState(x=>({...x,snapshots:x.snapshots.filter(v=>v.id!==s.id)}))})}><Trash2/></Button></div>):<div className="empty-state compact"><Save/><h3>{t("Пока нет точек")}</h3><p>{t("Первая пригодится перед развилкой или отъездом.")}</p></div>}</div></>}
</DialogContent></Dialog>
<Dialog open={detail!==null} onOpenChange={v=>{if(!v)setDetailId(null)}}><DialogContent closeLabel={t('Закрыть')} className="tracker-dialog achievement-dialog">{detail&&<><div className="detail-symbol"><Trophy/></div><span className="eyebrow">{detail.category} · {groups[detail.group]}</span><DialogTitle>{isHidden(detail)?t("Скрытое достижение"):detail.name}</DialogTitle><DialogDescription>{isHidden(detail)?t("Это достижение относится к более позднему этапу. Включи спойлеры, чтобы прочитать подробности."):detail.description}</DialogDescription>{isHidden(detail)?<Button variant="outline" onClick={()=>setState(s=>({...s,spoilers:true}))}><Eye/>{t("Открыть спойлеры")}</Button>:<>{state.earned.includes(detail.id)?<div className="complete-note"><CheckCheck size={18}/>{t("Достижение уже получено. Повторять действия не нужно.")}</div>:detail.steps?.length?<div className="instruction"><span className="eyebrow">{t("ПОШАГОВЫЙ ПЛАН")}</span><ol className="achievement-steps">{detail.steps.map((step,index)=><li key={step}><span>{pad(index+1)}</span><p>{step}</p></li>)}</ol></div>:<div className="instruction"><span className="eyebrow">{t("ЧТО ДЕЛАТЬ")}</span><p>{detail.tip}</p></div>}{runStatus(detail,state).detail&&<div className="book-warning"><Info size={17}/><p>{t(runStatus(detail,state).detail||'')}</p></div>}<div className="detail-meta"><span>{t("Когда")}</span><strong>{detail.stages.length>2?t("По ходу основной кампании"):detail.stages.map(id=>stages.find(s=>s.id===id)?.short).join(' / ')}</strong></div><div className="detail-actions">{AchievementMarks(detail)}</div></>}</>}</DialogContent></Dialog>
<Dialog open={confirm!==null} onOpenChange={v=>{if(!v)setConfirm(null)}}><DialogContent closeLabel={t('Закрыть')} className="tracker-dialog confirm-dialog"><DialogTitle>{confirm?.title}</DialogTitle><DialogDescription>{confirm?.body}</DialogDescription><div className="dialog-actions"><Button variant="outline" onClick={()=>setConfirm(null)}>{t("Отмена")}</Button><Button onClick={()=>{confirm?.action();setConfirm(null)}}>{t("Подтвердить")}</Button></div></DialogContent></Dialog>
<input ref={importInput} type="file" accept=".json,application/json" className="sr-only" tabIndex={-1} aria-label={t("Файл прогресса")} onChange={e=>void importProgress(e.target.files?.[0])}/>
{notice&&<div className="toast" role="status"><Info size={16}/>{t(notice)}</div>}
</div>;
}
