'use client';
import {useEffect,useRef,useState} from 'react';
import {PanelLeftOpen,PanelLeftClose,Compass,Trophy,Route,Layers,Save,Shield,ArrowUpRight,Swords,Eye,EyeOff,ChevronRight,Search,GitBranch,Database,Check,BookOpen,AlertTriangle,Download,Upload,Plus,RotateCcw,ExternalLink,Flag,Target,MapPin,LockKeyhole,CheckCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Breadcrumb,BreadcrumbList,BreadcrumbItem,BreadcrumbLink,BreadcrumbSeparator} from '@/components/ui/breadcrumb';
import {Checkbox} from '@/components/ui/checkbox';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption as Option} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {achievements,steps,items,stages,campaigns,events,decisionDefinitions,sources,checkedAt,type Locale,type Text,type Achievement,type Step} from '@/lib/witcher-data';
import {storageKey,freshState,parseState,activeRun,changeRun,mark,addRun,saveSnapshot,restoreSnapshot,availability,stepAvailability,type State,type Run,type Availability} from '@/lib/witcher-state';
import {translator,type CopyKey} from '@/lib/witcher-copy';
type Tab='now'|'achievements'|'route'|'collection';
type Modal={type:'achievement'|'step'|'item'|'event'|'restore';id:string}|{type:'runs'|'data'|'save'|'info'|'stage'}|null;
const statusKeys:Record<Availability['status'],CopyKey>={now:'statusNow',later:'statusLater',conditions:'statusConditions',blocked:'statusBlocked',mode:'statusMode',unknown:'statusUnknown'};
const initial=()=>{const s=freshState();s.runs[0].id='initial';s.activeRunId='initial';return s};
function SelectBox({value,onChange,label,children,disabled=false}:{value:string;onChange:(v:string)=>void;label:string;children:React.ReactNode;disabled?:boolean}){return <NativeSelect disabled={disabled} aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{children}</NativeSelect>}
export default function WitcherTracker(){
 const [state,setState]=useState<State>(initial),[locale,setLocale]=useState<Locale>('ru'),[ready,setReady]=useState(false),[loadFailed,setLoadFailed]=useState(false),[writeFailed,setWriteFailed]=useState(false);
 const [sidebarCollapsed,setSidebarCollapsed]=useState(false),[sidebarReady,setSidebarReady]=useState(false);
 const [tab,setTab]=useState<Tab>('now'),[modal,setModal]=useState<Modal>(null),[spoilers,setSpoilers]=useState(false),[revealed,setRevealed]=useState<string[]>([]),[message,setMessage]=useState<CopyKey|null>(null);
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[campaign,setCampaign]=useState('all'),[statusFilter,setStatusFilter]=useState('all'),[category,setCategory]=useState('all'),[region,setRegion]=useState('all'),[showDone,setShowDone]=useState(false);
 const [newName,setNewName]=useState(''),[newMode,setNewMode]=useState<Run['mode']>('standard'),[snapshotName,setSnapshotName]=useState(''),[pendingImport,setPendingImport]=useState<State|null>(null),[backedUp,setBackedUp]=useState(false);
 const currentRef=useRef(state),readyRef=useRef(false),blockedRef=useRef(false),rawRef=useRef<string|null>(null),fileRef=useRef<HTMLInputElement>(null);
 const t=translator(locale),txt=(v:Text)=>v[locale],run=activeRun(state),stage=stages.find(s=>s.id===run.stage)!;
 useEffect(()=>{try{const l=localStorage.getItem('sidequest.witcher3.language');if(l==='ru'||l==='uk'||l==='en')setLocale(l);setSpoilers(localStorage.getItem('sidequest.witcher3.spoilers')==='true');const raw=localStorage.getItem(storageKey);rawRef.current=raw;const loaded=raw?parseState(JSON.parse(raw)):freshState();if(!raw&&l==='uk')loaded.runs[0].name='Перше проходження';if(!raw&&l==='en')loaded.runs[0].name='First playthrough';currentRef.current=loaded;setState(loaded)}catch{blockedRef.current=true;setLoadFailed(true)}finally{readyRef.current=true;setReady(true)}},[]);
 useEffect(()=>{document.documentElement.lang=locale},[locale]);
 // Shell preferences are isolated from game progress and the Deus Ex sidebar.
 useEffect(()=>{try{setSidebarCollapsed(localStorage.getItem('sidequest.witcher3.sidebar-collapsed')==='true')}catch{}setSidebarReady(true)},[]);
 useEffect(()=>{if(sidebarReady)try{localStorage.setItem('sidequest.witcher3.sidebar-collapsed',String(sidebarCollapsed))}catch{}},[sidebarCollapsed,sidebarReady]);
 useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(null),7000);return()=>clearTimeout(timer)},[message]);
 useEffect(()=>{const prevent=(e:BeforeUnloadEvent)=>{if(writeFailed){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent)},[writeFailed]);
 function update(next:State,force=false){if(!readyRef.current||blockedRef.current&&!force)return;if(force){blockedRef.current=false;setLoadFailed(false)}currentRef.current=next;setState(next);try{localStorage.setItem(storageKey,JSON.stringify(next));rawRef.current=JSON.stringify(next);setWriteFailed(false)}catch{setWriteFailed(true)}}
 function patch(p:Partial<Run>){update(changeRun(currentRef.current,p))}
 function toggle(layer:'earned'|'completedSteps'|'completedStages'|'items',id:string,v:boolean){update(mark(currentRef.current,layer,[id],v))}
 function changeLanguage(l:string){if(l!=='ru'&&l!=='uk'&&l!=='en')return;setLocale(l);try{localStorage.setItem('sidequest.witcher3.language',l)}catch{}}
 function toggleSpoilers(){const next=!spoilers;setSpoilers(next);setRevealed([]);try{localStorage.setItem('sidequest.witcher3.spoilers',String(next))}catch{}}
 const visible=(id:string,secret?:boolean)=>!secret||spoilers||revealed.includes(id);
 const aName=(a:Achievement)=>visible(a.id,a.secret)?txt(a.name):t('hidden');
 function download(body:string,name:string){const url=URL.createObjectURL(new Blob([body],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function exportData(){download(loadFailed&&rawRef.current?rawRef.current:JSON.stringify(currentRef.current,null,2),`witcher3-${loadFailed?'original':'backup'}-${new Date().toISOString().slice(0,10)}.json`);setBackedUp(true)}
 async function importFile(file:File){try{if(file.size>2_000_000)throw Error();const parsed=parseState(JSON.parse(await file.text()));setPendingImport(parsed);setBackedUp(false);setModal({type:'data'})}catch{setMessage('invalid')}finally{if(fileRef.current)fileRef.current.value=''}}
 function checkpoint(){try{update(saveSnapshot(currentRef.current,snapshotName||`${txt(stage.name)} · ${new Date().toLocaleDateString(locale)}`));setSnapshotName('');setModal(null);setMessage('saved')}catch{setMessage('limit')}}
 function createRun(){try{update(addRun(currentRef.current,newName||t('newRun'),newMode));setNewName('');setModal(null)}catch{setMessage('limit')}}
 function goal(id:string,v:boolean){const r=activeRun(currentRef.current);patch({goals:v?[...new Set([...r.goals,id])]:r.goals.filter(x=>x!==id)})}
 function resetFilters(){setQuery('');setFilter('all');setCampaign('all');setStatusFilter('all');setCategory('all');setRegion('all')}
 function returnToNow(event:React.MouseEvent<HTMLAnchorElement>){if(!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&!event.altKey){event.preventDefault();setTab('now');resetFilters()}}
 const stageSteps=steps.filter(s=>s.stages.includes(run.stage as never)),primary=stageSteps.filter(s=>s.kind==='prepare').sort((a,b)=>Number(b.goals.some(id=>run.goals.includes(id)))-Number(a.goals.some(id=>run.goals.includes(id)))),otherSteps=stageSteps.filter(s=>s.kind==='action');
 const stageEvents=events.filter(e=>e.stage===run.stage&&!run.events.includes(e.id)),pendingSteps=stageSteps.filter(s=>!run.completedSteps.includes(s.id)),chosen=achievements.filter(a=>run.goals.includes(a.id)),disabled=!ready||loadFailed;
 const shownAchievements=achievements.filter(a=>{const shown=visible(a.id,a.secret);const text=shown?[txt(a.name),a.name.en,txt(a.description)].join(' '):t('hidden');return text.toLocaleLowerCase(locale).includes(query.trim().toLocaleLowerCase(locale))&&(campaign==='all'||a.campaign===campaign)&&(filter==='all'||filter==='unearned'&&!state.earned.includes(a.id)||filter==='obtained'&&state.earned.includes(a.id)||filter==='missable'&&a.missable||filter==='selected'&&run.goals.includes(a.id))&&(statusFilter==='all'||availability(a,run).status===statusFilter)&&(category==='all'||a.category===category)&&(region==='all'||a.stages.includes(region as never))});
 const shownItems=items.filter(i=>(region==='all'||i.region===region)&&(filter!=='unearned'||!run.items.includes(i.id))&&(visible(i.id,i.secret)?[txt(i.name),i.name.en,txt(i.location)].join(' '):t('hiddenItem')).toLocaleLowerCase(locale).includes(query.trim().toLocaleLowerCase(locale)));
 const badge=(a:Availability)=><span className={`wt-badge ${a.status}`}>{t(statusKeys[a.status])}</span>;
 const sourceLine=(source:keyof typeof sources)=><a className="wt-source-link" href={sources[source].url} target="_blank" rel="noreferrer">{t('source')} · {source==='steam'?'Steam':sources[source].name.split(' · ')[0]}<ExternalLink size={12}/></a>;
 function stepCard(s:Step){const shown=visible(s.id,s.secret),done=run.completedSteps.includes(s.id),status=stepAvailability(s,run);return <article className={`wt-task ${done?'done':''}`} key={s.id}><span className="wt-task-icon">{s.kind==='prepare'?<Compass size={19}/>:<Swords size={19}/>}</span><div><span className="wt-kicker">{t(s.kind==='prepare'?'prepare':'action')}{s.goals.some(id=>run.goals.includes(id))&&<> · <Target size={10}/></>}</span><Button variant="ghost" className="wt-title-button" onClick={()=>setModal({type:'step',id:s.id})}><h3>{shown?txt(s.title):t('hiddenStep')}</h3><ChevronRight size={14}/></Button><p>{shown?txt(s.detail):t('hiddenDesc')}</p>{status.status!=='now'&&badge(status)}</div><Checkbox disabled={disabled} checked={done} onCheckedChange={v=>toggle('completedSteps',s.id,v===true)} aria-label={`${t('markStep')}: ${shown?txt(s.title):t('hiddenStep')}`}/></article>}
 const empty=()=><div className="wt-empty"><Search/><h3>{t('noResults')}</h3><p>{t('noResultsHint')}</p><Button variant="outline" onClick={resetFilters}>{t('clearFilters')}</Button></div>;
 const revealButton=(id:string)=><div className="wt-hidden"><EyeOff/><p>{t('hiddenDesc')}</p><Button variant="outline" onClick={()=>setRevealed([...revealed,id])}><Eye size={15}/>{t('reveal')}</Button></div>;
 const searchBox=<label className="wt-search"><Search size={15}/><Input aria-label={t('search')} placeholder={t('search')} value={query} onChange={e=>setQuery(e.target.value)}/></label>;
 const regionSelect=<SelectBox value={region} label={t('allRegions')} onChange={setRegion}><Option value="all">{t('allRegions')}</Option>{stages.map(s=><Option key={s.id} value={s.id}>{txt(s.name)}</Option>)}</SelectBox>;
 const selectedAchievement=modal?.type==='achievement'?achievements.find(a=>a.id===modal.id):undefined,selectedStep=modal?.type==='step'?steps.find(s=>s.id===modal.id):undefined,selectedItem=modal?.type==='item'?items.find(i=>i.id===modal.id):undefined,selectedEvent=modal?.type==='event'?events.find(e=>e.id===modal.id):undefined,selectedSnapshot=modal?.type==='restore'?state.snapshots.find(s=>s.id===modal.id):undefined;
 const modalTitle=selectedAchievement?aName(selectedAchievement):selectedStep?visible(selectedStep.id,selectedStep.secret)?txt(selectedStep.title):t('hiddenStep'):selectedItem?visible(selectedItem.id,selectedItem.secret)?txt(selectedItem.name):t('hiddenItem'):selectedEvent?spoilers?txt(selectedEvent.title):t('confirmEvent'):selectedSnapshot?t('restore'):modal?.type==='runs'?t('runs'):modal?.type==='data'?t('data'):modal?.type==='save'?t('snapshot'):modal?.type==='stage'?t('selectStage'):t('coverage');
 return <div className={`wt ${sidebarCollapsed?'sidebar-collapsed':''}`}><a href="#witcher-main" className="wt-skip">{t('doNow')}</a>
 <aside id="wt-sidebar" className="wt-sidebar">
 <Button variant="ghost" size="icon" className="wt-sidebar-toggle" disabled={!sidebarReady} onClick={()=>setSidebarCollapsed(value=>!value)} aria-expanded={!sidebarCollapsed} aria-controls="wt-sidebar" aria-label={t(sidebarCollapsed?'expandSidebar':'collapseSidebar')} title={t(sidebarCollapsed?'expandSidebar':'collapseSidebar')}>{sidebarCollapsed?<PanelLeftOpen size={17}/>:<PanelLeftClose size={17}/>}</Button>
 <a href="/witcher-3" className="wt-brand" aria-label="The Witcher 3: Wild Hunt" onClick={returnToNow}><Swords/><span className="wt-brand-copy">{locale==='ru'?'ВЕДЬМАК':locale==='uk'?'ВІДЬМАК':'WITCHER'} <b>3</b><small>{locale==='ru'?'ДИКАЯ ОХОТА':locale==='uk'?'ДИКЕ ПОЛЮВАННЯ':'WILD HUNT'}</small></span></a>
 <div className="wt-label">{t('journal')}</div><nav aria-label={t('journal')}>{([{id:'now',icon:Compass},{id:'achievements',icon:Trophy},{id:'route',icon:Route},{id:'collection',icon:Layers}]as const).map(n=><Button key={n.id} variant="ghost" className={`wt-nav ${tab===n.id?'active':''}`} aria-label={t(n.id)} title={t(n.id)} aria-current={tab===n.id?'page':undefined} onClick={()=>{setTab(n.id);resetFilters()}}><n.icon size={18}/><span className="wt-nav-label">{t(n.id)}</span>{n.id==='achievements'&&<span className="wt-nav-count">{achievements.length}</span>}</Button>)}</nav>
 <div className="wt-subnav"><Button variant="ghost" onClick={()=>setModal({type:'runs'})} aria-label={t('runs')} title={t('runs')}><GitBranch size={15}/><span className="wt-nav-label">{t('runs')}</span><span className="wt-nav-count">{state.runs.length}</span></Button><Button variant="ghost" onClick={()=>setModal({type:'data'})} aria-label={t('data')} title={t('data')}><Database size={15}/><span className="wt-nav-label">{t('data')}</span></Button><Button variant="ghost" onClick={()=>setModal({type:'info'})} aria-label={t('coverage')} title={t('coverage')}><BookOpen size={15}/><span className="wt-nav-label">{t('coverage')}</span></Button></div>
 <div className="wt-sidebar-bottom"><Shield size={15}/><p>{ready?loadFailed?t('loadError'):writeFailed?t('writeError'):t('local'):t('loading')}</p></div><div className="wt-language"><span>LANGUAGE</span><SelectBox value={locale} label="Language / Мова / Язык" onChange={changeLanguage}><Option value="ru">RU</Option><Option value="uk">UA</Option><Option value="en">EN</Option></SelectBox></div></aside>
 <div className="wt-workspace"><header className="wt-top"><div className="wt-top-navigation"><Breadcrumb className="wt-breadcrumb" aria-label={t('siteNavigation')}><BreadcrumbList><BreadcrumbItem><BreadcrumbLink href="/">{t('home')}</BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator>{' > '}</BreadcrumbSeparator><BreadcrumbItem><BreadcrumbLink href="/witcher-3" aria-current="page" onClick={returnToNow}>The Witcher 3: Wild Hunt</BreadcrumbLink></BreadcrumbItem></BreadcrumbList></Breadcrumb></div><div className="wt-top-actions"><Button variant="ghost" onClick={toggleSpoilers} aria-pressed={spoilers} aria-label={t(spoilers?'spoilersOn':'spoilersOff')}>{spoilers?<Eye size={15}/>:<EyeOff size={15}/>}<span>{t(spoilers?'spoilersOn':'spoilersOff')}</span></Button><Button variant="outline" disabled={disabled} onClick={()=>setModal({type:'save'})}><Save size={15}/>{t('snapshot')}</Button></div></header><main id="witcher-main" className="wt-main">
 {(loadFailed||writeFailed)&&<div className="wt-warning" role="alert"><AlertTriangle/><div><p>{t(loadFailed?'loadError':'writeError')}</p><Button variant="outline" onClick={()=>setModal({type:'data'})}>{t('data')}</Button></div></div>}
 <h1 className="sr-only">{tab==='now'?t('location'):t(tab)}</h1>
 <section className="wt-stage"><div className="wt-stage-art" aria-hidden="true"/><span className="wt-stage-number">{String(stages.findIndex(s=>s.id===run.stage)+1).padStart(2,'0')}</span><div className="wt-stage-copy"><span className="wt-kicker">{t('location')}</span><h2>{txt(stage.name)}</h2><p>{txt(stage.hint)}</p></div><Button variant="outline" onClick={()=>setModal({type:'stage'})} aria-label={t('selectStage')}><MapPin size={14}/><span>{t('selectStage')}</span></Button></section>
 <div className="wt-stats">{[{label:'earned',hint:'earnedHint',value:state.earned.length,total:achievements.length},{label:'stepCount',hint:'stepHint',value:run.completedSteps.length,total:steps.length},{label:'stageCount',hint:'stageHint',value:run.completedStages.length,total:stages.length}].map(v=><div key={v.label}><span>{t(v.label as CopyKey)}</span><strong>{v.value}<small> / {v.total}</small></strong><Progress value={v.value/v.total*100} aria-label={t(v.label as CopyKey)}/><p>{t(v.hint as CopyKey)}</p></div>)}</div>
 <div className="wt-grid"><section className="wt-primary">
 {tab==='now'&&<><div className="wt-section-title"><h2>{t('doNow')}</h2><span>{pendingSteps.length} {t('remaining').toLocaleUpperCase(locale)}</span></div>{run.goals.includes('walked-the-path')&&run.difficultyBroken!=='no'&&<div className="wt-warning"><Shield/><div><strong>{t('difficulty')}</strong><p>{t('difficultyHint')}</p></div></div>}{stageEvents.length>0&&<div className="wt-warning wt-blue"><Flag/><div><strong>{t('events')}</strong><p>{t('eventHint')}</p><Button variant="link" onClick={()=>setTab('route')}>{t('details')}<ArrowUpRight size={13}/></Button></div></div>}<label className="wt-inline-check"><Checkbox checked={showDone} onCheckedChange={v=>setShowDone(v===true)}/>{t('showDone')}</label><div className="wt-task-list">{primary.filter(s=>showDone||!run.completedSteps.includes(s.id)).map(stepCard)}</div>{primary.every(s=>run.completedSteps.includes(s.id))&&<div className="wt-empty compact"><CheckCheck/><h3>{t('stageDone')}</h3><p>{t('stageDoneHint')}</p></div>}<details className="wt-other"><summary>{t('moreActions')}<span>{otherSteps.filter(s=>!run.completedSteps.includes(s.id)).length}</span></summary>{otherSteps.filter(s=>showDone||!run.completedSteps.includes(s.id)).map(stepCard)}</details></>}
 {tab==='achievements'&&<><div className="wt-section-title"><h2>{t('achievements')}</h2><span>{shownAchievements.length} / {achievements.length}</span></div><div className="wt-filters">{searchBox}<SelectBox value={filter} label={t('achievements')} onChange={setFilter}>{(['all','unearned','obtained','missable','selected']as const).map(k=><Option key={k} value={k}>{t(k)}</Option>)}</SelectBox><SelectBox value={campaign} label={t('allCampaigns')} onChange={setCampaign}><Option value="all">{t('allCampaigns')}</Option>{Object.entries(campaigns).map(([k,v])=><Option key={k} value={k}>{txt(v)}</Option>)}</SelectBox><SelectBox value={statusFilter} label={t('allStatuses')} onChange={setStatusFilter}><Option value="all">{t('allStatuses')}</Option>{Object.entries(statusKeys).map(([k,v])=><Option key={k} value={k}>{t(v)}</Option>)}</SelectBox>{regionSelect}<SelectBox value={category} label={t('type')} onChange={setCategory}><Option value="all">{t('type')}: {t('all')}</Option>{(['story','combat','explore','gwent']as const).map(k=><Option key={k} value={k}>{t(k==='gwent'?'gwentType':k)}</Option>)}</SelectBox></div>{shownAchievements.length===0?empty():<div className="wt-task-list">{shownAchievements.map(a=>{const shown=visible(a.id,a.secret);return <article className={`wt-task wt-achievement ${state.earned.includes(a.id)?'done':''}`} key={a.id}>{shown?<img className="wt-achievement-icon" src={a.icon} alt="" loading="lazy" width={44} height={44}/>:<span className="wt-task-icon"><LockKeyhole size={18}/></span>}<div><span className="wt-kicker">{txt(campaigns[a.campaign])}</span><Button variant="ghost" className="wt-title-button" onClick={()=>setModal({type:'achievement',id:a.id})}><h3>{aName(a)}</h3><ChevronRight size={14}/></Button><p>{shown?txt(a.description):t('hiddenDesc')}</p><div className="wt-tags">{badge(availability(a,run))}{a.missable&&<span className="wt-badge missable">{t('missable')}</span>}{run.goals.includes(a.id)&&<Target size={12}/>}</div></div><Checkbox disabled={disabled} checked={state.earned.includes(a.id)} onCheckedChange={v=>toggle('earned',a.id,v===true)} aria-label={`${t('markEarned')}: ${aName(a)}`}/></article>})}</div>}</>}
 {tab==='route'&&<><div className="wt-section-title"><h2>{t('route')}</h2><span>01 — {stages.length}</span></div><p className="wt-helper">{t('navigationOnly')}</p><div className="wt-route-list">{stages.map((s,i)=><article className={`wt-route-row ${s.id===run.stage?'active':''}`} key={s.id}><span className="wt-route-number">{String(i+1).padStart(2,'0')}</span><div><span className="wt-kicker">{txt(campaigns[s.campaign])}</span><Button variant="ghost" className="wt-title-button" disabled={disabled} onClick={()=>patch({stage:s.id})}><h3>{txt(s.name)}</h3>{s.id===run.stage?<span className="wt-badge now">{t('current')}</span>:<ChevronRight size={15}/>}</Button><p>{txt(s.hint)}</p></div><Checkbox disabled={disabled} checked={run.completedStages.includes(s.id)} onCheckedChange={v=>toggle('completedStages',s.id,v===true)} aria-label={`${t('markStage')}: ${txt(s.name)}`}/></article>)}</div><div className="wt-section-title wt-spaced"><h2>{t('events')}</h2></div><p className="wt-helper">{t('eventHint')}</p>{events.filter(e=>e.stage===run.stage).map((e,i)=><div className="wt-event" key={e.id}><Flag size={18}/><div><h3>{spoilers?txt(e.title):`${t('confirmEvent')} ${i+1}`}</h3><p>{spoilers?txt(e.warning):t('hiddenDesc')}</p></div><Button variant="outline" disabled={disabled||run.events.includes(e.id)} onClick={()=>setModal({type:'event',id:e.id})}>{run.events.includes(e.id)?<><Check size={15}/>{t('confirmed')}</>:t('confirm')}</Button></div>)}{!events.some(e=>e.stage===run.stage)&&<p className="wt-helper">{t('stageDoneHint')}</p>}<div className="wt-section-title wt-spaced"><h2>{t('decisions')}</h2></div><p className="wt-helper">{t('decisionHint')}</p>{decisionDefinitions.filter(d=>(d.stages as readonly string[]).includes(run.stage)).map(d=><div className="wt-decision" key={d.id}><label htmlFor={`decision-${d.id}`}>{txt(d.label)}</label><NativeSelect id={`decision-${d.id}`} disabled={disabled} value={run.decisions[d.id]??'unknown'} onChange={e=>patch({decisions:{...run.decisions,[d.id]:e.target.value}})}><Option value="unknown">{t('unknown')}</Option>{d.options.map(([v,label])=><Option key={v} value={v}>{txt(label)}</Option>)}</NativeSelect><p>{spoilers?txt(d.effect):t('decisionHint')}</p>{!spoilers&&<Button variant="link" onClick={()=>setSpoilers(true)}>{t('reveal')}</Button>}</div>)}</>}
 {tab==='collection'&&<><div className="wt-collection-intro"><span className="wt-kicker">GWENT / {t('prioritySet').toLocaleUpperCase(locale)}</span><h2>{t('gwent')}</h2><span className="wt-badge missable">{t('partial')}</span><p>{t('collectionHint')}</p><div className="wt-collection-total"><strong>{run.items.length}<small> / {items.length}</small></strong><span>{t('got')}</span></div><Progress value={run.items.length/items.length*100} aria-label={t('prioritySet')}/><p className="wt-scope">{t('collectionScope')}</p></div><div className="wt-filters">{searchBox}{regionSelect}<SelectBox value={filter} label={t('collection')} onChange={setFilter}><Option value="all">{t('all')}</Option><Option value="unearned">{t('unearned')}</Option></SelectBox></div>{shownItems.length===0?empty():shownItems.map(i=><article className={`wt-task ${run.items.includes(i.id)?'done':''}`} key={i.id}><span className="wt-task-icon"><Layers size={19}/></span><div><span className="wt-kicker">{txt(stages.find(s=>s.id===i.region)!.name)}</span><Button variant="ghost" className="wt-title-button" onClick={()=>setModal({type:'item',id:i.id})}><h3>{visible(i.id,i.secret)?txt(i.name):t('hiddenItem')}</h3><ChevronRight size={14}/></Button><p>{visible(i.id,i.secret)?txt(i.location):t('hiddenDesc')}</p><span className={`wt-badge ${run.items.includes(i.id)?'now':'unknown'}`}>{run.items.includes(i.id)?t('got'):i.event&&run.events.includes(i.event)?t('itemClosed'):t('itemAvailable')}</span></div><Checkbox disabled={disabled} checked={run.items.includes(i.id)} onCheckedChange={v=>toggle('items',i.id,v===true)} aria-label={`${t('markItem')}: ${visible(i.id,i.secret)?txt(i.name):t('hiddenItem')}`}/></article>)}</>}
 </section><aside className="wt-rail"><section className="wt-panel wt-goals"><span className="wt-kicker"><Target size={12}/>{t('focuses')}</span><h3>{t('goals')}</h3><p>{t('goalHint')}</p>{chosen.map(a=><div className="wt-goal-row" key={a.id}><label><Checkbox disabled={disabled} checked onCheckedChange={v=>goal(a.id,v===true)}/><span>{aName(a)}</span></label>{badge(availability(a,run))}</div>)}<Button variant="link" onClick={()=>{setTab('achievements');resetFilters()}}><Plus size={13}/>{t('goals')}<ArrowUpRight size={13}/></Button>{run.goals.includes('last-action-hero')&&run.goals.includes('kling-of-the-clink')&&<p className="wt-risk">{t('goalConflict')}</p>}</section>
 <section className="wt-panel"><span className="wt-kicker"><Shield size={12}/>{t('conditions')}</span><label className="wt-field-label">{t('difficulty')}</label><SelectBox disabled={disabled} label={t('difficulty')} value={run.difficulty} onChange={v=>patch({difficulty:v as Run['difficulty'],difficultyBroken:'unknown'})}><Option value="unknown">{t('unknown')}</Option><Option value="death">{t('death')}</Option><Option value="hard">{t('hard')}</Option><Option value="other">{t('other')}</Option></SelectBox><label className="wt-field-label">{t('lowered')}</label><SelectBox disabled={disabled} label={t('lowered')} value={run.difficultyBroken} onChange={v=>patch({difficultyBroken:v as Run['difficultyBroken']})}><Option value="unknown">{t('unknown')}</Option><Option value="no">{t('clean')}</Option><Option value="yes">{t('broken')}</Option></SelectBox><p className="wt-small-note">{t('difficultyHint')}</p></section>
 <section className="wt-panel wt-before"><span className="wt-kicker"><Flag size={12}/>{t('before')}</span><h3>{txt(stage.name)}</h3><div className="wt-before-row"><span>{t('remaining')}</span><strong>{pendingSteps.length}</strong></div><p>{t('saveGame')}</p><Button variant="outline" disabled={disabled} onClick={()=>setModal({type:'save'})}><Save size={14}/>{t('snapshot')}</Button></section><section className="wt-notes"><label className="wt-kicker" htmlFor="witcher-notes">{t('notes')}</label><Textarea id="witcher-notes" disabled={disabled} maxLength={30000} value={run.notes} onChange={e=>patch({notes:e.target.value})} placeholder={t('notesPlaceholder')}/></section></aside></div>
 <footer className="wt-footer"><span>{t('footer')}</span><Button variant="link" onClick={()=>setModal({type:'info'})}>{t('coverage')}<ArrowUpRight size={12}/></Button></footer></main></div>
 <Dialog open={modal!==null} onOpenChange={open=>{if(!open){setModal(null);setPendingImport(null)}}}><DialogContent className="wt-dialog" closeLabel={t('close')}><DialogTitle>{modalTitle}</DialogTitle><DialogDescription>{selectedAchievement||selectedStep?t('nextCheck'):selectedItem?t('collectionScope'):selectedSnapshot?t('restoreHint'):selectedEvent?t('eventUnmarked'):modal?.type==='save'?t('saveGame'):modal?.type==='runs'?t('newRunHint'):modal?.type==='data'?t('exportHint'):modal?.type==='stage'?t('navigationOnly'):t('coverageHint')}</DialogDescription>
 {selectedAchievement&&<>{!visible(selectedAchievement.id,selectedAchievement.secret)?revealButton(selectedAchievement.id):<><p className="wt-detail-description">{txt(selectedAchievement.description)}</p>{badge(availability(selectedAchievement,run))}{availability(selectedAchievement,run).reasons.map((r,i)=><p className="wt-detail-reason" key={i}>{txt(r)}</p>)}<h3 className="wt-dialog-subtitle">{t('checkedSteps')}</h3>{steps.filter(s=>s.goals.includes(selectedAchievement.id)).map(s=><label className="wt-check-row" key={s.id}><Checkbox disabled={disabled} checked={run.completedSteps.includes(s.id)} onCheckedChange={v=>toggle('completedSteps',s.id,v===true)}/><span>{visible(s.id,s.secret)?txt(s.title):t('hiddenStep')}</span><Button variant="ghost" size="icon" aria-label={t('details')} onClick={()=>setModal({type:'step',id:s.id})}><ChevronRight size={14}/></Button></label>)}<div className="wt-detail-meta"><span>{t('verified')}: {checkedAt}</span><span>Steam · 292030</span><span>{t(selectedAchievement.source==='steam'?'official':'guideBased')}</span></div>{sourceLine(selectedAchievement.source)}</>}<label className="wt-check-row"><Checkbox disabled={disabled} checked={run.goals.includes(selectedAchievement.id)} onCheckedChange={v=>goal(selectedAchievement.id,v===true)}/>{t('selected')}</label><label className="wt-check-row wt-earned-check"><Checkbox disabled={disabled} checked={state.earned.includes(selectedAchievement.id)} onCheckedChange={v=>toggle('earned',selectedAchievement.id,v===true)}/>{t('markEarned')}</label></>}
 {selectedStep&&<>{!visible(selectedStep.id,selectedStep.secret)?revealButton(selectedStep.id):<><p className="wt-detail-description">{txt(selectedStep.detail)}</p>{badge(stepAvailability(selectedStep,run))}{stepAvailability(selectedStep,run).reasons.map((r,i)=><p key={i}>{txt(r)}</p>)}<h3 className="wt-dialog-subtitle">{t('related')}</h3>{selectedStep.goals.map(id=>{const a=achievements.find(a=>a.id===id)!;return <Button className="wt-related" variant="outline" key={id} onClick={()=>setModal({type:'achievement',id})}>{aName(a)}<ChevronRight size={14}/></Button>})}{sourceLine(selectedStep.source)}</>}<label className="wt-check-row"><Checkbox disabled={disabled} checked={run.completedSteps.includes(selectedStep.id)} onCheckedChange={v=>toggle('completedSteps',selectedStep.id,v===true)}/>{t('markStep')}</label></>}
 {selectedItem&&<>{!visible(selectedItem.id,selectedItem.secret)?revealButton(selectedItem.id):<><p className="wt-detail-description">{txt(selectedItem.location)}</p><p>{txt(stages.find(s=>s.id===selectedItem.region)!.name)} · {t('prioritySet')}</p>{sourceLine(selectedItem.source)}</>}<label className="wt-check-row"><Checkbox disabled={disabled} checked={run.items.includes(selectedItem.id)} onCheckedChange={v=>toggle('items',selectedItem.id,v===true)}/>{t('markItem')}</label></>}
 {modal?.type==='stage'&&<div className="wt-stage-options">{stages.map((s,i)=><Button key={s.id} variant="outline" disabled={disabled} className={run.stage===s.id?'active':''} onClick={()=>{patch({stage:s.id});setModal(null)}}><span>{String(i+1).padStart(2,'0')}</span>{txt(s.name)}{run.stage===s.id&&<Check size={14}/>}</Button>)}</div>}
 {modal?.type==='save'&&<><Input aria-label={t('name')} value={snapshotName} maxLength={100} placeholder={`${txt(stage.name)} · ${new Date().toLocaleDateString(locale)}`} onChange={e=>setSnapshotName(e.target.value)}/><Button disabled={disabled||state.snapshots.length>=100} onClick={checkpoint}><Save size={14}/>{t('save')}</Button></>}
 {modal?.type==='runs'&&<><div className="wt-run-list">{state.runs.map(r=><Button key={r.id} variant="outline" disabled={disabled} className={r.id===run.id?'active':''} onClick={()=>{update({...currentRef.current,activeRunId:r.id});setModal(null)}}><GitBranch size={14}/><span>{r.name}<small>{txt(stages.find(s=>s.id===r.stage)!.name)} · {t(r.mode==='ngplus'?'ngplus':'standard')}</small></span>{r.id===run.id&&<Check size={15}/>}</Button>)}</div><h3 className="wt-dialog-subtitle">{t('newRun')}</h3><Input maxLength={100} aria-label={t('runName')} value={newName} onChange={e=>setNewName(e.target.value)} placeholder={t('runName')}/><SelectBox value={newMode} label={t('type')} onChange={v=>setNewMode(v as Run['mode'])}><Option value="standard">{t('standard')}</Option><Option value="ngplus">{t('ngplus')}</Option></SelectBox>{newMode==='ngplus'&&<p>{t('ngHint')}</p>}<Button disabled={disabled||state.runs.length>=30} onClick={createRun}><Plus size={14}/>{t('create')}</Button></>}
 {modal?.type==='data'&&<><div className="wt-transfer"><Button variant="outline" onClick={exportData}><Download size={15}/>{t(loadFailed?'rawBackup':'export')}</Button><Button variant="outline" onClick={()=>fileRef.current?.click()}><Upload size={15}/>{t('import')}</Button></div>{pendingImport&&<section className="wt-import-preview"><h3>{t('importTitle')}</h3><p>{pendingImport.runs.length} {t('runs')} · {pendingImport.earned.length} {t('obtained')} · {pendingImport.snapshots.length} {t('checkpoints')}</p><p>{t('importHint')}</p><Button variant="outline" onClick={exportData}><Download size={15}/>{t('backupFirst')}</Button><Button disabled={!backedUp} onClick={()=>{update(pendingImport,true);setPendingImport(null);setModal(null);setMessage('imported')}}>{t('replace')}</Button></section>}<h3 className="wt-dialog-subtitle">{t('checkpoints')} · {state.snapshots.length}/100</h3><p>{t('saveGame')}</p>{!state.snapshots.length&&<p>{t('noCheckpoints')}</p>}{state.snapshots.map(s=><div className="wt-snapshot-row" key={s.id}><div><strong>{s.name}</strong><p>{s.run.name} · {new Date(s.createdAt).toLocaleString(locale)}</p></div><Button variant="outline" disabled={disabled} onClick={()=>setModal({type:'restore',id:s.id})}><RotateCcw size={14}/>{t('restore')}</Button></div>)}</>}
 {selectedSnapshot&&<><p className="wt-detail-description">{selectedSnapshot.name}</p><div className="wt-dialog-actions"><Button variant="outline" onClick={()=>setModal({type:'data'})}>{t('cancel')}</Button><Button disabled={disabled} onClick={()=>{update(restoreSnapshot(currentRef.current,selectedSnapshot.id));setModal(null);setMessage('restored')}}><RotateCcw size={15}/>{t('restore')}</Button></div></>}
 {selectedEvent&&<>{spoilers||revealed.includes(selectedEvent.id)?<><p className="wt-detail-description">{txt(selectedEvent.warning)}</p><ul className="wt-preflight">{steps.filter(s=>s.before===selectedEvent.id&&!run.completedSteps.includes(s.id)).map(s=><li key={s.id}>{visible(s.id,s.secret)?txt(s.title):t('hiddenStep')}</li>)}{items.filter(i=>i.event===selectedEvent.id&&!run.items.includes(i.id)).map(i=><li key={i.id}>{visible(i.id,i.secret)?txt(i.name):t('hiddenItem')}</li>)}</ul></>:revealButton(selectedEvent.id)}<p>{t('saveGame')}</p><div className="wt-dialog-actions"><Button variant="outline" onClick={()=>setModal({type:'save'})}>{t('snapshot')}</Button><Button disabled={disabled} onClick={()=>{patch({events:[...new Set([...run.events,selectedEvent.id])]});setModal(null);setMessage('completedEvent')}}>{t('confirmEvent')}</Button></div></>}
 {modal?.type==='info'&&<><p>{t('collectionHint')}</p><p>{t('languageNote')}</p><div className="wt-detail-meta"><span>Steam 292030 · {checkedAt}</span><span>{t('manual')}</span></div>{Object.entries(sources).map(([id,s],i)=><a className="wt-source-link" href={s.url} key={id} target="_blank" rel="noreferrer">{String(i+1).padStart(2,'0')} · {s.name.split(' · ')[0]}<ExternalLink size={13}/></a>)}<p>© CD PROJEKT RED. {t('footer')}</p></>}
 </DialogContent></Dialog><input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f)}}/>{message&&<div className="wt-toast" role="status"><Check size={16}/>{t(message)}<Button variant="ghost" size="icon" onClick={()=>setMessage(null)} aria-label={t('close')}>×</Button></div>}</div>;
}
