export type MapLocale='ru'|'uk'|'en';
export type MapText=Record<MapLocale,string>;
export type MapMarkerKind='mission'|'achievement'|'collectible'|'poi'|'transition';

export type MapLayer={id:string;label:MapText;image:string;aspectRatio:string;planeWidth:number;initialZoom:number};
export type MapMarker={id:string;x:number;y:number;height?:number;kind:MapMarkerKind;title:MapText;location:MapText;description:MapText;mission?:string;achievement?:MapText;layers?:string[]};
export type MapScene={id:string;code:string;label:MapText;stageIds:string[];layers:MapLayer[];markers:MapMarker[]};

const text=(ru:string,uk:string,en:string):MapText=>({ru,uk,en});
const marker=(id:string,x:number,y:number,kind:MapMarkerKind,title:MapText,location:MapText,description:MapText,options:Partial<MapMarker>={}):MapMarker=>({id,x,y,kind,title,location,description,...options});

export const mapScenes:MapScene[]=[
  {
    id:'prague',code:'PRG',label:text('Прага','Прага','Prague'),stageIds:['prague1','prague2','prague3'],
    layers:[
      {id:'visit1',label:text('Первое посещение','Перше відвідування','First visit'),image:'/maps/prague-visit-1.png',aspectRatio:'3 / 2',planeWidth:96,initialZoom:.78},
      {id:'visit2',label:text('Второе посещение','Друге відвідування','Second visit'),image:'/maps/prague-visit-2.png',aspectRatio:'3 / 2',planeWidth:96,initialZoom:.78},
      {id:'visit3',label:text('Третье посещение','Третє відвідування','Third visit'),image:'/maps/prague-visit-3.png',aspectRatio:'3 / 2',planeWidth:96,initialZoom:.78},
      {id:'infrastructure',label:text('Инфраструктура','Інфраструктура','Infrastructure'),image:'/maps/prague-infrastructure.png',aspectRatio:'3 / 2',planeWidth:96,initialZoom:.78},
      {id:'overview',label:text('Районы','Райони','Districts'),image:'/maps/prague-overview.png',aspectRatio:'3 / 2',planeWidth:88,initialZoom:.88},
    ],
    markers:[
      marker('jensen',37,66,'poi',text('Дом Дженсена','Дім Дженсена','Jensen’s apartment'),text('Зелень, квартира 41','Зелень, квартира 41','Zeleň, apartment 41'),text('Точка возвращения между заданиями. Здесь начинаются несколько побочных цепочек, а в квартире лежат сюжетные предметы и коллекционные материалы.','Точка повернення між завданнями. Тут починаються кілька побічних ланцюжків, а у квартирі лежать сюжетні предмети та колекційні матеріали.','A hub between missions. Several side-mission chains begin here, and the apartment contains story items and collectibles.'),{mission:'M2 / SM06 / SM10'}),
      marker('tf29',48,17,'mission',text('Штаб ОГ-29','Штаб ОГ-29','TF29 Headquarters'),text('Подземный комплекс под Praha Dovoz','Підземний комплекс під Praha Dovoz','Underground facility below Praha Dovoz'),text('Главная рабочая база Дженсена в Праге. Через скрытый считыватель в транспортной конторе открывается лифт в подземный штаб.','Головна робоча база Дженсена у Празі. Через прихований зчитувач у транспортній конторі відкривається ліфт до підземного штабу.','Jensen’s main Prague base. A concealed reader in the shipping storefront unlocks the elevator to the underground headquarters.'),{mission:'M4 / M9 / M14'}),
      marker('ruzicka',43,27,'mission',text('Вокзал Ружичка','Вокзал Ружичка','Růžička Station'),text('Северная Прага','Північна Прага','Northern Prague'),text('Место расследования после взрыва. Серверная и служебные зоны содержат улики, терминалы и коллекционные предметы.','Місце розслідування після вибуху. Серверна та службові зони містять докази, термінали й колекційні предмети.','The bombing investigation site. Its server room and restricted areas contain evidence, terminals, and collectibles.'),{mission:'M5',layers:['visit1']}),
      marker('time-machine',50,84,'achievement',text('Машина времени','Машина часу','The Time Machine'),text('Пржеказка','Пржеказка','Překážka'),text('Мастерская Вацлава Коллера. Здесь восстанавливаются аугментации Дженсена и продолжается цепочка калибратора.','Майстерня Вацлава Коллера. Тут відновлюються аугментації Дженсена й продовжується ланцюжок калібратора.','Václav Koller’s workshop. Jensen’s augmentations are repaired here and the calibrator quest continues.'),{mission:'M3 / SM03 / SM08',achievement:text('Честь превыше всего','Честь понад усе','Honor Holds Us All')}),
      marker('richard',58,37,'achievement',text('Убежище Ричарда','Сховище Річарда','Richard’s refuge'),text('Канализация Чиста Чтврт','Каналізація Чіста Чтврт','Čistá Čtvrť sewers'),text('Подземная сцена культа. Сначала найди Либорио у дома Дженсена, сорви плакат и поговори с ним; затем возвращайся сюда с рабочими глушителями.','Підземна сцена культу. Спочатку знайди Ліборіо біля дому Дженсена, зірви плакат і поговори з ним; потім повертайся сюди з робочими глушниками.','The cult’s underground stage. First find Liborio near Jensen’s home, tear down the poster and talk to him; then return with the signal scramblers working.'),{mission:'SM02',achievement:text('Культ личности','Культ особистості','Cult of Personality'),layers:['visit1','visit2','infrastructure']}),
      marker('otar',62,44,'achievement',text('Подпольное казино Отара','Підпільне казино Отара','Otar’s underground casino'),text('Канализация Чиста Чтврт','Каналізація Чіста Чтврт','Čistá Čtvrť sewers'),text('Здесь решается способ получения калибратора. Сделка с Отаром запускает цепочку услуг, необходимую для «Всё в семье».','Тут вирішується спосіб отримання калібратора. Угода з Отаром запускає ланцюжок послуг, потрібний для «Усе в родині».','This is where the calibrator route is decided. A deal with Otar starts the favors required for All in the Family.'),{mission:'SM04 / SM09',achievement:text('Всё в семье','Усе в родині','All in the Family'),layers:['visit1','visit2','infrastructure']}),
      marker('palisade',14,28,'mission',text('Банк «Пэлисейд»','Банк «Палісейд»','Palisade Property Bank'),text('Чиста Чтврт','Чіста Чтврт','Čistá Čtvrť'),text('Многоуровневый банк с корпоративными хранилищами, исполнительскими сейфами и тайным кабинетом директора. Банковская ветка M12 открывает обязательные книги.','Багаторівневий банк із корпоративними сховищами, виконавчими сейфами та таємним кабінетом директора. Банківська гілка M12 відкриває обов’язкові книги.','A multi-level bank with corporate vaults, executive safes and a hidden CEO room. The M12 bank route opens required eBooks.'),{mission:'M12',achievement:text('Коллекционер планшетов','Колекціонер планшетів','Tablet Collector'),layers:['visit1','visit2','visit3','overview']}),
      marker('church',30,84,'mission',text('Церковь Бога-Машины','Церква Бога-Машини','Church of the MachineGod'),text('Южная Прага','Південна Прага','Southern Prague'),text('Основная зона M11. Книги на верхних этажах доступны во время задания или после завершения альтернативного ограбления банка.','Головна зона M11. Книги на верхніх поверхах доступні під час завдання або після завершення альтернативного пограбування банку.','The main M11 location. Upper-floor eBooks are accessible during the mission or after completing the alternative bank heist.'),{mission:'M11',achievement:text('Коллекционер планшетов','Колекціонер планшетів','Tablet Collector'),layers:['visit2','visit3','overview']}),
      marker('dvali',91,55,'mission',text('Театр «Двали»','Театр «Двалі»','Dvali Theater'),text('Квартал красных фонарей','Квартал червоних ліхтарів','Red Light District'),text('Штаб Радича Николадзе. Здесь проходят финальные шаги «Всё в семье» и часть третьего визита в Прагу.','Штаб Радича Ніколадзе. Тут проходять фінальні кроки «Усе в родині» та частина третього візиту до Праги.','Radich Nikoladze’s headquarters. The final All in the Family steps and part of the third Prague visit take place here.'),{mission:'SM09 / M14',achievement:text('Всё в семье','Усе в родині','All in the Family'),layers:['visit2','visit3','overview']}),
      marker('red-queen',78,58,'mission',text('«Красная королева»','«Червона королева»','The Red Queen'),text('Квартал красных фонарей','Квартал червоних ліхтарів','Red Light District'),text('Клуб и центральная точка ночного района. Связан с расследованиями Neon Nights и Fade to Black.','Клуб і центральна точка нічного району. Пов’язаний із розслідуваннями Neon Nights і Fade to Black.','A club and the hub of the night district, linked to the Neon Nights and Fade to Black investigations.'),{mission:'SM00 / SM07',layers:['visit2','visit3','overview']}),
      marker('libuse',76,34,'collectible',text('Апартаменты «Либуше»','Апартаменти «Лібуше»','Libuše Apartments'),text('Давны','Давни','Dávný'),text('Жилой комплекс с квартирами, скрытыми проходами и коллекционными предметами. Здесь находится квартира 96 с набором Praxis.','Житловий комплекс із квартирами, прихованими проходами та колекційними предметами. Тут розташована квартира 96 з набором Praxis.','An apartment block with hidden routes and collectibles. Apartment 96 contains a Praxis kit.'),{layers:['visit1','visit2','visit3','overview']}),
      marker('monument',47,47,'transition',text('Станция «Монумент»','Станція «Монумент»','Monument Station'),text('Железнодорожный узел','Залізничний вузол','Rail junction'),text('Переход между северной и южной частями Праги. Доступность районов и событий меняется между тремя визитами.','Перехід між північною та південною частинами Праги. Доступність районів і подій змінюється між трьома візитами.','A transfer point between northern and southern Prague. District and event availability changes across the three visits.'),{layers:['visit1','visit2','visit3','infrastructure','overview']}),
    ]
  },
  {
    id:'dubai',code:'DBX',label:text('Дубай','Дубай','Dubai'),stageIds:['dubai'],
    layers:[{id:'mission',label:text('Все уровни','Усі рівні','All levels'),image:'/maps/dubai-annotated.png',aspectRatio:'29 / 74',planeWidth:48,initialZoom:.58}],
    markers:[
      marker('dubai-entry',53,13,'mission',text('Технический вход','Технічний вхід','Service entrance'),text('Уровень 3','Рівень 3','Level 3'),text('Начало операции в недостроенном отеле. Верхние технические помещения ведут к атриуму и зоне сделки.','Початок операції у недобудованому готелі. Верхні технічні приміщення ведуть до атріуму та зони угоди.','The operation begins in the unfinished hotel. Upper service areas lead toward the atrium and the deal.'),{mission:'M1'}),
      marker('dubai-panel',67,28,'achievement',text('Первая кодовая панель','Перша кодова панель','First keypad'),text('Уровень 2','Рівень 2','Level 2'),text('Введи классический код 0451 на первой доступной панели, чтобы получить достижение.','Введи класичний код 0451 на першій доступній панелі, щоб отримати досягнення.','Enter the classic code 0451 on the first available keypad to unlock the achievement.'),{achievement:text('Горячая комбинация','Гаряча комбінація','A Heated Combination')}),
      marker('dubai-tutorial',59,51,'achievement',text('Учебные эпизоды','Навчальні епізоди','Tutorial opportunities'),text('Атриум и пентхаусы','Атріум і пентхауси','Atrium and penthouses'),text('Используй все предлагаемые обучающие эпизоды до финальной перестрелки. Пропуск одного из них закрывает достижение в этой попытке.','Використай усі запропоновані навчальні епізоди до фінальної перестрілки. Пропуск одного з них закриває досягнення в цій спробі.','Complete every offered tutorial opportunity before the final firefight. Missing one prevents the achievement in this attempt.'),{achievement:text('Адепт метавселенной','Адепт метавсесвіту','Adept of the Metaverse')}),
      marker('dubai-singh',62,92,'achievement',text('Сингх и вертолёт','Сінгх і гелікоптер','Singh and the helicopter'),text('Нижний атриум','Нижній атріум','Lower atrium'),text('Сразу доберись до вертолёта, извлеки батарею и не дай Сингху погибнуть. Не задерживайся на противниках.','Одразу дістанься гелікоптера, витягни батарею й не дай Сінгху загинути. Не затримуйся на противниках.','Reach the helicopter immediately, remove its battery and keep Singh alive. Do not get delayed by the enemies.'),{achievement:text('Его песня ещё не спета','Його пісню ще не проспівано','Singh No Swan Song')})
    ]
  },
  {
    id:'golem',code:'GCM',label:text('Голем-Сити','Голем-Сіті','Golem City'),stageIds:['golem'],
    layers:[
      {id:'throat',label:text('Глотка: уровни 1–7','Глотка: рівні 1–7','The Throat: levels 1–7'),image:'/maps/golem-throat.png',aspectRatio:'15 / 4',planeWidth:110,initialZoom:.62},
      {id:'ridit',label:text('Станция Ридит','Станція Рідит','Ridit Station'),image:'/maps/golem-ridit.png',aspectRatio:'16 / 57',planeWidth:42,initialZoom:.45},
    ],
    markers:[
      marker('golem-throat-route',28,48,'mission',text('Подъём через Глотку','Підйом через Глотку','Climb through the Throat'),text('ARC: вертикальный жилой сектор','ARC: вертикальний житловий сектор','ARC vertical housing sector'),text('Основной путь вглубь территории ARC проходит через семь уровней, мосты и технические обходы.','Головний шлях углиб території ARC проходить через сім рівнів, мости й технічні обходи.','The main route into ARC territory crosses seven levels, bridges and maintenance bypasses.'),{mission:'M7',layers:['throat']}),
      marker('rookery',54,56,'achievement',text('Золотой пингвин','Золотий пінгвін','Golden penguin'),text('Глотка → тайное гнездо','Глотка → таємне гніздо','The Throat → hidden rookery'),text('Перенеси золотого пингвина через комплекс и помести его в скрытое гнездо. Награда открывает тайник с Praxis.','Перенеси золотого пінгвіна через комплекс і поклади його до прихованого гнізда. Нагорода відкриває схованку з Praxis.','Carry the golden penguin through the complex and place it in the hidden rookery. The reward opens a Praxis cache.'),{achievement:text('Золотая клетка','Золота клітка','The Golden Rookery'),layers:['throat']}),
      marker('ridit-entry',50,84,'mission',text('Вход в станцию Ридит','Вхід до станції Рідит','Ridit Station entrance'),text('Уровень 1','Рівень 1','Level 1'),text('Внутри есть несколько маршрутов к северному лифту: через охрану, технические шахты и верхние этажи.','Усередині є кілька маршрутів до північного ліфта: через охорону, технічні шахти й верхні поверхи.','Several routes lead to the north elevator through security, service shafts and upper floors.'),{mission:'M7',layers:['ridit']}),
      marker('rucker',48,13,'achievement',text('Кабинет Талоса Рукера','Кабінет Талоса Рукера','Talos Rucker’s office'),text('Ти Захрада','Ти Захрада','Ty Zahrada'),text('Исследуй кабинет и проведи разговор так, чтобы Рукер раскрыл сведения. После сцены забери ключ-карту и проверь тайную комнату.','Досліди кабінет і проведи розмову так, щоб Рукер розкрив відомості. Після сцени забери ключ-картку й перевір таємну кімнату.','Search the office and steer the conversation so Rucker reveals information. After the scene, take his keycard and inspect the hidden room.'),{achievement:text('Переговорщик','Перемовник','The Golden Rookery route'),layers:['ridit']})
    ]
  },
  {
    id:'garm',code:'GRM',label:text('G.A.R.M.','G.A.R.M.','G.A.R.M.'),stageIds:['garm'],
    layers:[{id:'facility',label:text('Комплекс: все уровни','Комплекс: усі рівні','Facility: all levels'),image:'/maps/garm-annotated.png',aspectRatio:'3 / 7',planeWidth:50,initialZoom:.6}],
    markers:[
      marker('garm-contact',28,27,'achievement',text('Связь после пробуждения','Зв’язок після пробудження','Call after waking'),text('Вход в комплекс','Вхід до комплексу','Facility entrance'),text('Позвони Алексу Веге, чтобы избежать сюжетной тревоги во втором ангаре. Звонок Миллеру делает скрытное прохождение сложнее.','Зателефонуй Алекс Везі, щоб уникнути сюжетної тривоги у другому ангарі. Дзвінок Міллеру ускладнює приховане проходження.','Call Alex Vega to avoid the scripted alarm in Hangar 2. Calling Miller makes a stealth run harder.'),{achievement:text('Проныра','Пронира','Foxiest of the Hounds')}),
      marker('garm-drill',34,78,'achievement',text('Пульт ледового бура','Пульт льодового бура','Ice-drill controls'),text('Ангар 1','Ангар 1','Hangar 1'),text('Включи бур и проложи новый проход через лёд в ангар 2. Убедись, что зона перед буром свободна.','Увімкни бур і проклади новий прохід крізь лід до ангара 2. Переконайся, що зона перед буром вільна.','Activate the drill to open a new route through the ice into Hangar 2. Make sure the area in front of it is clear.'),{achievement:text('Бурильщик','Бурильник','Core Driller')}),
      marker('garm-exit',76,10,'transition',text('Вертолётная площадка','Вертолітний майданчик','Helipad'),text('За ангаром 2','За ангаром 2','Beyond Hangar 2'),text('Финальная точка выхода из комплекса после пересечения обоих ангаров и ледового тоннеля.','Фінальна точка виходу з комплексу після перетину обох ангарів і льодового тунелю.','The facility exit after crossing both hangars and the ice tunnel.'),{mission:'M13'})
    ]
  },
  {
    id:'london',code:'LDN',label:text('Лондон','Лондон','London'),stageIds:['london'],
    layers:[{id:'apex',label:text('Apex Centre: все уровни','Apex Centre: усі рівні','Apex Centre: all levels'),image:'/maps/london-annotated.png',aspectRatio:'5 / 32',planeWidth:30,initialZoom:.35}],
    markers:[
      marker('london-security',49,29,'mission',text('Служебные этажи','Службові поверхи','Service floors'),text('Apex Centre','Apex Centre','Apex Centre'),text('Перед финальной развилкой можно обезвредить одиннадцать поддельных охранников и подготовить безопасный путь к делегатам.','Перед фінальною розвилкою можна знешкодити одинадцять підроблених охоронців і підготувати безпечний шлях до делегатів.','Before the final split, neutralize the eleven fake guards and prepare a safe route to the delegates.'),{mission:'M15'}),
      marker('london-delegates',51,52,'achievement',text('Делегаты','Делегати','Delegates'),text('Защищённый конференц-зал','Захищений конференц-зал','Secured conference room'),text('Доберись сюда после разговора с Миллером и останови отравление «Орхидеей». Затем немедленно направляйся к Марченко.','Дістанься сюди після розмови з Міллером і зупини отруєння «Орхідеєю». Потім негайно прямуй до Марченка.','Reach this room after speaking with Miller and stop the Orchid poisoning. Then head straight for Marchenko.'),{mission:'M17',achievement:text('Палка сразу в двух колёсах','Палиця одразу у двох колесах','Spokes in Two Wheels')}),
      marker('london-marchenko',50,89,'achievement',text('Выставочный зал','Виставковий зал','Exhibition Hall'),text('Нижний уровень Apex Centre','Нижній рівень Apex Centre','Lower Apex Centre'),text('Финальная встреча с Марченко. Останови детонатор вовремя; устройство убийства Марченко даёт отдельный летальный исход.','Фінальна зустріч із Марченком. Зупини детонатор вчасно; пристрій убивства Марченка дає окремий летальний результат.','The final confrontation with Marchenko. Stop the detonator in time; the Marchenko kill switch provides a separate lethal outcome.'),{mission:'M16',achievement:text('Палка сразу в двух колёсах / Механизм из Лапуты','Палиця одразу у двох колесах / Механізм із Лапути','Spokes in Two Wheels / Laputan Machine')})
    ]
  }
];

export const mapSources=[
  {label:'Deus Ex Wiki — Mankind Divided maps',href:'https://deusex.fandom.com/wiki/Category:Deus_Ex:_Mankind_Divided_maps'},
  {label:'Deus Ex Wiki — Mankind Divided walkthrough',href:'https://deusex.fandom.com/wiki/Deus_Ex:_Mankind_Divided_walkthrough'}
];
