import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import ts from 'typescript';
const dir=path.resolve('.checks/witcher');
fs.mkdirSync(dir,{recursive:true});
fs.writeFileSync(path.join(dir,'package.json'),'{"type":"commonjs"}');
for(const file of ['witcher-data','witcher-copy','witcher-state'])fs.writeFileSync(path.join(dir,`${file}.js`),ts.transpileModule(fs.readFileSync(`lib/${file}.ts`,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText);
fs.copyFileSync('lib/witcher-steam.json',path.join(dir,'witcher-steam.json'));
const require=createRequire(import.meta.url);
const data=require(path.join(dir,'witcher-data.js'));
const model=require(path.join(dir,'witcher-state.js'));
const {copy}=require(path.join(dir,'witcher-copy.js'));
const {achievements,steps,items,stages,decisionDefinitions,events}=data;
const {freshState,activeRun,changeRun,mark,addRun,saveSnapshot,restoreSnapshot,parseState,availability,stepAvailability,evaluate}=model;
const achievement=id=>{const a=achievements.find(a=>a.id===id);assert(a,id);return a};
assert.equal(achievements.length,78);
assert.deepEqual(Object.fromEntries(['base','hos','baw'].map(c=>[c,achievements.filter(a=>a.campaign===c).length])),{base:52,hos:13,baw:13});
for(const entries of [achievements,steps,items,stages,events,decisionDefinitions])assert.equal(new Set(entries.map(a=>a.id)).size,entries.length);
assert.equal(items.length,11);
for(const s of steps){assert(s.stages.length);for(const id of s.stages)assert(stages.some(x=>x.id===id));for(const id of s.goals)achievement(id);assert(!achievements.some(a=>a.id===s.id),'Independent step ids');if(s.before)assert(events.some(e=>e.id===s.before))}
for(const i of items){assert(stages.some(s=>s.id===i.region));for(const id of i.goals)achievement(id);if(i.event)assert(events.some(e=>e.id===i.event))}
for(const record of [...achievements,...steps,...items,...stages])for(const key of ['name','description','title','detail','hint','location'])if(record[key])for(const locale of ['ru','uk','en'])assert.equal(typeof record[key][locale],'string',`${record.id}.${key}.${locale}`);
for(const [key,value]of Object.entries(copy))for(const locale of ['ru','uk','en'])assert(value[locale]?.length,`${key}.${locale}`);
for(const a of achievements){for(const l of ['ru','uk','en'])assert(a.name[l]&&a.description[l],`Missing localized achievement ${a.id}.${l}`);assert(steps.some(s=>s.goals.includes(a.id)))}
console.log('PASS: 78 achievements (52/13/13), independent stable IDs, 11 unique cards, all links and three languages.');
let s=freshState();assert.equal(availability(achievement('walked-the-path'),activeRun(s)).status,'unknown');
const original=structuredClone(s);
s=mark(s,'earned',['full-crew'],true);assert.deepEqual(s.runs,original.runs);assert.equal(activeRun(s).completedSteps.length,0);
s=mark(s,'completedSteps',['keira-invite'],true);assert.deepEqual(s.earned,['full-crew']);assert.deepEqual(activeRun(s).decisions,{});
s=mark(s,'completedStages',['velen'],true);assert.equal(activeRun(s).stage,'orchard');assert.equal(activeRun(s).events.length,0);
s=changeRun(s,{stage:'allies'});assert.deepEqual(activeRun(s).completedStages,['velen']);assert.deepEqual(activeRun(s).events,[]);
s=saveSnapshot(s,'Before choice');const snap=s.snapshots[0];
s=changeRun(s,{decisions:{keira:'other',ves:'dead',ruler:'ignored'},notes:'branch note'});
assert.equal(availability(achievement('full-crew'),activeRun(s)).status,'blocked');assert(s.earned.includes('full-crew'));
assert(availability(achievement('full-crew'),activeRun(s)).reasons.length>=3,'All blocking reasons are evaluated');
s=mark(s,'earned',['card-collector'],true);s=mark(s,'items',items.map(i=>i.id),true);
const beforeRestore=structuredClone(s);s=restoreSnapshot(s,snap.id);assert.deepEqual(s.earned,beforeRestore.earned);assert.deepEqual(activeRun(s),snap.run);assert.equal(activeRun(s).items.length,0);
const oldId=activeRun(s).id;s=addRun(s,'Another run','standard');assert.equal(s.runs.length,2);assert.notEqual(activeRun(s).id,oldId);assert.deepEqual(s.earned,beforeRestore.earned);assert.equal(activeRun(s).completedSteps.length,0);assert.equal(activeRun(s).completedStages.length,0);assert.equal(activeRun(s).notes,'');
s=mark(s,'items',['milva'],true);s=mark(s,'items',['milva'],true);assert.deepEqual(activeRun(s).items,['milva']);assert.equal(s.runs.find(r=>r.id===oldId).items.length,0);
const beforeNg=structuredClone(s);s=addRun(s,'NG+','ngplus');assert.deepEqual(s.earned,beforeNg.earned);assert.deepEqual(activeRun(s).items,[]);assert.equal(s.runs.length,3);
const fresh=freshState();const allItems=mark(fresh,'items',items.map(i=>i.id),true);assert.deepEqual(allItems.earned,[]);const allSteps=mark(allItems,'completedSteps',steps.map(i=>i.id),true);assert.deepEqual(allSteps.earned,[]);
assert.deepEqual(parseState(JSON.parse(JSON.stringify(s))),s);
assert.deepEqual(parseState(JSON.parse(JSON.stringify(allSteps))),allSteps);
console.log('PASS: independent archive/actions/stages/cards, independent runs, NG+, checkpoint rollback and round-trip import.');
for(const mutate of [v=>v.game='deus-ex',v=>v.platform='ps5',v=>v.version=2,v=>v.catalogVersion=2,v=>v.profile='someone-else',v=>v.runs=[],v=>v.activeRunId='bad',v=>v.earned=['invented'],v=>v.earned=['full-crew','full-crew'],v=>v.runs[0].items=['fake'],v=>v.runs[0].completedSteps=['full-crew'],v=>v.runs[0].stage='fake',v=>v.runs[0].decisions.keira='both',v=>v.runs[0].difficultyBroken='maybe',v=>v.runs[0].goals=['fake'],v=>v.runs[0].notes='x'.repeat(30001),v=>v.snapshots[0].run.id='missing',v=>v.snapshots[0].createdAt='not-a-date',v=>v.runs.push(structuredClone(v.runs[0]))]){const bad=structuredClone(s),unchanged=JSON.stringify(s);mutate(bad);assert.throws(()=>parseState(bad));assert.equal(JSON.stringify(s),unchanged)}
assert.throws(()=>mark(s,'earned',['bad'],true));assert.throws(()=>restoreSnapshot(s,'bad'));
console.log('PASS: invalid imports (game, platform, version, profile, bounds, duplicates, linked IDs) cannot mutate progress.');
const run=activeRun(freshState());run.stage='finale';run.difficulty='death';run.difficultyBroken='no';assert.equal(availability(achievement('walked-the-path'),run).status,'now');assert.equal(availability(achievement('ran-the-gauntlet'),run).status,'now');
run.difficultyBroken='yes';run.completedSteps.push('check-difficulty');assert.equal(availability(achievement('walked-the-path'),run).status,'blocked');assert.equal(availability(achievement('ran-the-gauntlet'),run).status,'unknown','Dropping from Death March does not prove failure of the lower threshold');
run.difficulty='hard';assert.equal(availability(achievement('ran-the-gauntlet'),run).status,'blocked');run.difficultyBroken='no';assert.equal(availability(achievement('walked-the-path'),run).status,'mode');
run.decisions={spirit:'ritual'};assert.equal(availability(achievement('woodland-spirit'),run).status,'blocked');assert.notEqual(availability(achievement('geralt-the-professional'),run).status,'blocked');
run.decisions={ending:'prison'};assert.equal(availability(achievement('last-action-hero'),run).status,'blocked');run.decisions={ending:'medal'};assert.equal(availability(achievement('kling-of-the-clink'),run).status,'blocked');
run.events=['masquerade'];run.items=[];assert.equal(availability(achievement('card-collector'),run).status,'unknown','Missing marks are not proof of lost cards');run.items=items.map(i=>i.id);assert.equal(availability(achievement('card-collector'),run).status,'unknown','Partial collection is not complete');
run.events=['isle'];run.completedSteps=[];run.decisions={};assert.equal(stepAvailability(steps.find(s=>s.id==='keira-invite'),run).status,'unknown');
const a={fact:'a',equals:'yes'},b={fact:'b',equals:'yes'};
assert.equal(evaluate(a,{}),null);assert.equal(evaluate({all:[a,b]},{a:'no'}),false);assert.equal(evaluate({all:[a,b]},{a:'yes'}),null);assert.equal(evaluate({any:[a,b]},{a:'yes'}),true);assert.equal(evaluate({any:[a,b]},{a:'no'}),null);assert.equal(evaluate({not:a},{}),null);assert.equal(evaluate({atLeast:1,of:[a,b]},{b:'yes'}),true);assert.equal(evaluate({atLeast:2,of:[a,b]},{a:'no'}),false);assert.equal(evaluate({atLeast:2,of:[a,b]},{a:'yes'}),null);
console.log('PASS: persistent difficulty conditions, all blocker reasons, branch conflicts, unknown data and three-valued expression rules.');
const ui=fs.readFileSync('components/witcher-tracker.tsx','utf8');
assert(ui.includes('const shown=visible(a.id,a.secret);const text=shown?'),'Search must use spoiler-gated content');
assert(ui.includes("visible(i.id,i.secret)?[txt(i.name),i.name.en,txt(i.location)]"),'Collection search must be spoiler-gated');
assert(ui.includes('blockedRef.current&&!force'),'Load failures prevent overwrites');
assert(ui.includes('disabled={!backedUp}'),'Import requires a backup before replacement');
assert(ui.includes("setRevealed([])"),'Turning off spoilers clears individual reveals');
console.log('PASS: source-level spoiler/search and storage safeguards. Browser UI testing not performed.');
